// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool AnimKitPriorityRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Priority, sizeof(m_Priority), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading AnimKitPriority", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* AnimKitPriorityRec::GetFilename() {
	return "DBFilesClient\\AnimKitPriority.dbc";
}
