// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool AreaPOIRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempName_langIndices[16];
	uint32_t tempDescription_langIndices[16];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Importance, sizeof(m_Importance), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[0], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[1], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[2], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[3], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[4], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[5], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[6], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[7], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Icon[8], sizeof(m_Icon[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_FactionID, sizeof(m_FactionID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Pos[0], sizeof(m_Pos[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Pos[1], sizeof(m_Pos[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Pos[2], sizeof(m_Pos[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ContinentID, sizeof(m_ContinentID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Flags, sizeof(m_Flags), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID, sizeof(m_AreaID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[1], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[2], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[3], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[4], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[5], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[6], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[7], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[8], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[9], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[10], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[11], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[12], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[13], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[14], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[15], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Name_lang_bitmask, sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[1], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[2], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[3], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[4], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[5], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[6], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[7], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[8], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[9], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[10], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[11], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[12], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[13], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[14], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescription_langIndices[15], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Description_lang_bitmask, sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_WorldStateID, sizeof(m_WorldStateID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_WorldMapLink, sizeof(m_WorldMapLink), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading AreaPOI", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_Name_lang[0] = &stringBuffer[tempName_langIndices[0]];
		m_Name_lang[1] = &stringBuffer[tempName_langIndices[1]];
		m_Name_lang[2] = &stringBuffer[tempName_langIndices[2]];
		m_Name_lang[3] = &stringBuffer[tempName_langIndices[3]];
		m_Name_lang[4] = &stringBuffer[tempName_langIndices[4]];
		m_Name_lang[5] = &stringBuffer[tempName_langIndices[5]];
		m_Name_lang[6] = &stringBuffer[tempName_langIndices[6]];
		m_Name_lang[7] = &stringBuffer[tempName_langIndices[7]];
		m_Name_lang[8] = &stringBuffer[tempName_langIndices[8]];
		m_Name_lang[9] = &stringBuffer[tempName_langIndices[9]];
		m_Name_lang[10] = &stringBuffer[tempName_langIndices[10]];
		m_Name_lang[11] = &stringBuffer[tempName_langIndices[11]];
		m_Name_lang[12] = &stringBuffer[tempName_langIndices[12]];
		m_Name_lang[13] = &stringBuffer[tempName_langIndices[13]];
		m_Name_lang[14] = &stringBuffer[tempName_langIndices[14]];
		m_Name_lang[15] = &stringBuffer[tempName_langIndices[15]];
		m_Description_lang[0] = &stringBuffer[tempDescription_langIndices[0]];
		m_Description_lang[1] = &stringBuffer[tempDescription_langIndices[1]];
		m_Description_lang[2] = &stringBuffer[tempDescription_langIndices[2]];
		m_Description_lang[3] = &stringBuffer[tempDescription_langIndices[3]];
		m_Description_lang[4] = &stringBuffer[tempDescription_langIndices[4]];
		m_Description_lang[5] = &stringBuffer[tempDescription_langIndices[5]];
		m_Description_lang[6] = &stringBuffer[tempDescription_langIndices[6]];
		m_Description_lang[7] = &stringBuffer[tempDescription_langIndices[7]];
		m_Description_lang[8] = &stringBuffer[tempDescription_langIndices[8]];
		m_Description_lang[9] = &stringBuffer[tempDescription_langIndices[9]];
		m_Description_lang[10] = &stringBuffer[tempDescription_langIndices[10]];
		m_Description_lang[11] = &stringBuffer[tempDescription_langIndices[11]];
		m_Description_lang[12] = &stringBuffer[tempDescription_langIndices[12]];
		m_Description_lang[13] = &stringBuffer[tempDescription_langIndices[13]];
		m_Description_lang[14] = &stringBuffer[tempDescription_langIndices[14]];
		m_Description_lang[15] = &stringBuffer[tempDescription_langIndices[15]];
		return true;
	}
	m_Name_lang[0] = "";
	m_Name_lang[1] = "";
	m_Name_lang[2] = "";
	m_Name_lang[3] = "";
	m_Name_lang[4] = "";
	m_Name_lang[5] = "";
	m_Name_lang[6] = "";
	m_Name_lang[7] = "";
	m_Name_lang[8] = "";
	m_Name_lang[9] = "";
	m_Name_lang[10] = "";
	m_Name_lang[11] = "";
	m_Name_lang[12] = "";
	m_Name_lang[13] = "";
	m_Name_lang[14] = "";
	m_Name_lang[15] = "";
	m_Description_lang[0] = "";
	m_Description_lang[1] = "";
	m_Description_lang[2] = "";
	m_Description_lang[3] = "";
	m_Description_lang[4] = "";
	m_Description_lang[5] = "";
	m_Description_lang[6] = "";
	m_Description_lang[7] = "";
	m_Description_lang[8] = "";
	m_Description_lang[9] = "";
	m_Description_lang[10] = "";
	m_Description_lang[11] = "";
	m_Description_lang[12] = "";
	m_Description_lang[13] = "";
	m_Description_lang[14] = "";
	m_Description_lang[15] = "";
	return true;
}

const char* AreaPOIRec::GetFilename() {
	return "DBFilesClient\\AreaPOI.dbc";
}
