// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool AreaAssignmentRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MapID, sizeof(m_MapID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID, sizeof(m_AreaID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ChunkX, sizeof(m_ChunkX), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ChunkY, sizeof(m_ChunkY), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading AreaAssignment", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* AreaAssignmentRec::GetFilename() {
	return "DBFilesClient\\AreaAssignment.dbc";
}
