// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool CharHairGeosetsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RaceID, sizeof(m_RaceID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SexID, sizeof(m_SexID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_VariationID, sizeof(m_VariationID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GeosetID, sizeof(m_GeosetID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Showscalp, sizeof(m_Showscalp), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading CharHairGeosets", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* CharHairGeosetsRec::GetFilename() {
	return "DBFilesClient\\CharHairGeosets.dbc";
}
