// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool CreatureMovementInfoRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SmoothFacingChaseRate, sizeof(m_SmoothFacingChaseRate), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading CreatureMovementInfo", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* CreatureMovementInfoRec::GetFilename() {
	return "DBFilesClient\\CreatureMovementInfo.dbc";
}
