// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool DeathThudLookupsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SizeClass, sizeof(m_SizeClass), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_TerrainTypeSoundID, sizeof(m_TerrainTypeSoundID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SoundEntryID, sizeof(m_SoundEntryID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SoundEntryIDWater, sizeof(m_SoundEntryIDWater), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading DeathThudLookups", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* DeathThudLookupsRec::GetFilename() {
	return "DBFilesClient\\DeathThudLookups.dbc";
}
