// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool DungeonMapRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MapID, sizeof(m_MapID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_FloorIndex, sizeof(m_FloorIndex), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MinX, sizeof(m_MinX), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MaxX, sizeof(m_MaxX), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MinY, sizeof(m_MinY), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MaxY, sizeof(m_MaxY), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ParentWorldMapID, sizeof(m_ParentWorldMapID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading DungeonMap", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* DungeonMapRec::GetFilename() {
	return "DBFilesClient\\DungeonMap.dbc";
}
