// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool EnvironmentalDamageRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EnumID, sizeof(m_EnumID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_VisualkitID, sizeof(m_VisualkitID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading EnvironmentalDamage", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* EnvironmentalDamageRec::GetFilename() {
	return "DBFilesClient\\EnvironmentalDamage.dbc";
}
