// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool FootstepTerrainLookupRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CreatureFootstepID, sizeof(m_CreatureFootstepID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_TerrainSoundID, sizeof(m_TerrainSoundID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SoundID, sizeof(m_SoundID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SoundIDSplash, sizeof(m_SoundIDSplash), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading FootstepTerrainLookup", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* FootstepTerrainLookupRec::GetFilename() {
	return "DBFilesClient\\FootstepTerrainLookup.dbc";
}
