// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool gtOCTRegenHPRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_Data, sizeof(m_Data), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading gtOCTRegenHP", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* gtOCTRegenHPRec::GetFilename() {
	return "DBFilesClient\\gtOCTRegenHP.dbc";
}
