// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool ItemRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ClassID, sizeof(m_ClassID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SubclassID, sizeof(m_SubclassID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Sound_override_subclassID, sizeof(m_Sound_override_subclassID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Material, sizeof(m_Material), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_DisplayInfoID, sizeof(m_DisplayInfoID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_InventoryType, sizeof(m_InventoryType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SheatheType, sizeof(m_SheatheType), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading Item", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* ItemRec::GetFilename() {
	return "DBFilesClient\\Item.dbc";
}
