// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool LightRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ContinentID, sizeof(m_ContinentID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GameCoords[0], sizeof(m_GameCoords[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GameCoords[1], sizeof(m_GameCoords[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GameCoords[2], sizeof(m_GameCoords[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GameFalloffStart, sizeof(m_GameFalloffStart), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GameFalloffEnd, sizeof(m_GameFalloffEnd), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[0], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[1], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[2], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[3], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[4], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[5], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[6], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LightParamsID[7], sizeof(m_LightParamsID[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading Light", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* LightRec::GetFilename() {
	return "DBFilesClient\\Light.dbc";
}
