// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool LiquidMaterialRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LVF, sizeof(m_LVF), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Flags, sizeof(m_Flags), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading LiquidMaterial", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* LiquidMaterialRec::GetFilename() {
	return "DBFilesClient\\LiquidMaterial.dbc";
}
