// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool LoadingScreenTaxiSplinesRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_PathID, sizeof(m_PathID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[0], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[1], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[2], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[3], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[4], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[5], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[6], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locx[7], sizeof(m_Locx[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[0], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[1], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[2], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[3], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[4], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[5], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[6], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Locy[7], sizeof(m_Locy[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_LegIndex, sizeof(m_LegIndex), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading LoadingScreenTaxiSplines", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* LoadingScreenTaxiSplinesRec::GetFilename() {
	return "DBFilesClient\\LoadingScreenTaxiSplines.dbc";
}
