// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool MovieVariationRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MovieID, sizeof(m_MovieID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_FileDataID, sizeof(m_FileDataID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading MovieVariation", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* MovieVariationRec::GetFilename() {
	return "DBFilesClient\\MovieVariation.dbc";
}
