// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool NamesProfanityRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempNameIndices[1];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempNameIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Language, sizeof(m_Language), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading NamesProfanity", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_Name = &stringBuffer[tempNameIndices[0]];
		return true;
	}
	return true;
}

const char* NamesProfanityRec::GetFilename() {
	return "DBFilesClient\\NamesProfanity.dbc";
}
