// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool ParticleColorRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Start[0], sizeof(m_Start[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Start[1], sizeof(m_Start[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Start[2], sizeof(m_Start[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MID[0], sizeof(m_MID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MID[1], sizeof(m_MID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MID[2], sizeof(m_MID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_End[0], sizeof(m_End[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_End[1], sizeof(m_End[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_End[2], sizeof(m_End[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading ParticleColor", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* ParticleColorRec::GetFilename() {
	return "DBFilesClient\\ParticleColor.dbc";
}
