// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool PowerDisplayRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempGlobalStringBaseTagIndices[1];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ActualType, sizeof(m_ActualType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempGlobalStringBaseTagIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Red, sizeof(m_Red), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Green, sizeof(m_Green), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Blue, sizeof(m_Blue), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading PowerDisplay", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_GlobalStringBaseTag = &stringBuffer[tempGlobalStringBaseTagIndices[0]];
		return true;
	}
	m_GlobalStringBaseTag = "";
	return true;
}

const char* PowerDisplayRec::GetFilename() {
	return "DBFilesClient\\PowerDisplay.dbc";
}
