// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool QuestSortRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempSortName_langIndices[17];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[1], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[2], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[3], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[4], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[5], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[6], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[7], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[8], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[9], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[10], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[11], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[12], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[13], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[14], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[15], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempSortName_langIndices[16], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading QuestSort", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_SortName_lang[0] = &stringBuffer[tempSortName_langIndices[0]];
		m_SortName_lang[1] = &stringBuffer[tempSortName_langIndices[1]];
		m_SortName_lang[2] = &stringBuffer[tempSortName_langIndices[2]];
		m_SortName_lang[3] = &stringBuffer[tempSortName_langIndices[3]];
		m_SortName_lang[4] = &stringBuffer[tempSortName_langIndices[4]];
		m_SortName_lang[5] = &stringBuffer[tempSortName_langIndices[5]];
		m_SortName_lang[6] = &stringBuffer[tempSortName_langIndices[6]];
		m_SortName_lang[7] = &stringBuffer[tempSortName_langIndices[7]];
		m_SortName_lang[8] = &stringBuffer[tempSortName_langIndices[8]];
		m_SortName_lang[9] = &stringBuffer[tempSortName_langIndices[9]];
		m_SortName_lang[10] = &stringBuffer[tempSortName_langIndices[10]];
		m_SortName_lang[11] = &stringBuffer[tempSortName_langIndices[11]];
		m_SortName_lang[12] = &stringBuffer[tempSortName_langIndices[12]];
		m_SortName_lang[13] = &stringBuffer[tempSortName_langIndices[13]];
		m_SortName_lang[14] = &stringBuffer[tempSortName_langIndices[14]];
		m_SortName_lang[15] = &stringBuffer[tempSortName_langIndices[15]];
		m_SortName_lang[16] = &stringBuffer[tempSortName_langIndices[16]];
		return true;
	}
	return true;
}

const char* QuestSortRec::GetFilename() {
	return "DBFilesClient\\QuestSort.dbc";
}
