// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SoundProviderPreferencesRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempDescriptionIndices[1];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempDescriptionIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Flags, sizeof(m_Flags), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAXEnvironmentSelection, sizeof(m_EAXEnvironmentSelection), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAXDecayTime, sizeof(m_EAXDecayTime), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2EnvironmentSize, sizeof(m_EAX2EnvironmentSize), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2EnvironmentDiffusion, sizeof(m_EAX2EnvironmentDiffusion), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2Room, sizeof(m_EAX2Room), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2RoomHF, sizeof(m_EAX2RoomHF), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2DecayHFRatio, sizeof(m_EAX2DecayHFRatio), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2Reflections, sizeof(m_EAX2Reflections), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2ReflectionsDelay, sizeof(m_EAX2ReflectionsDelay), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2Reverb, sizeof(m_EAX2Reverb), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2ReverbDelay, sizeof(m_EAX2ReverbDelay), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2RoomRolloff, sizeof(m_EAX2RoomRolloff), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX2AirAbsorption, sizeof(m_EAX2AirAbsorption), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3RoomLF, sizeof(m_EAX3RoomLF), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3DecayLFRatio, sizeof(m_EAX3DecayLFRatio), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3EchoTime, sizeof(m_EAX3EchoTime), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3EchoDepth, sizeof(m_EAX3EchoDepth), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3ModulationTime, sizeof(m_EAX3ModulationTime), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3ModulationDepth, sizeof(m_EAX3ModulationDepth), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3HFReference, sizeof(m_EAX3HFReference), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EAX3LFReference, sizeof(m_EAX3LFReference), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SoundProviderPreferences", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_Description = &stringBuffer[tempDescriptionIndices[0]];
		return true;
	}
	m_Description = "";
	return true;
}

const char* SoundProviderPreferencesRec::GetFilename() {
	return "DBFilesClient\\SoundProviderPreferences.dbc";
}
