// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellIconRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempTextureFilenameIndices[1];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempTextureFilenameIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellIcon", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_TextureFilename = &stringBuffer[tempTextureFilenameIndices[0]];
		return true;
	}
	return true;
}

const char* SpellIconRec::GetFilename() {
	return "DBFilesClient\\SpellIcon.dbc";
}
