// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellCategoryRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Flags, sizeof(m_Flags), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellCategory", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellCategoryRec::GetFilename() {
	return "DBFilesClient\\SpellCategory.dbc";
}
