// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellClassOptionsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ModalNextSpell, sizeof(m_ModalNextSpell), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SpellClassMask[0], sizeof(m_SpellClassMask[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SpellClassMask[1], sizeof(m_SpellClassMask[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SpellClassMask[2], sizeof(m_SpellClassMask[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SpellClassSet, sizeof(m_SpellClassSet), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellClassOptions", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellClassOptionsRec::GetFilename() {
	return "DBFilesClient\\SpellClassOptions.dbc";
}
