// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool TransportPhysicsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_WaveAmp, sizeof(m_WaveAmp), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_WaveTimeScale, sizeof(m_WaveTimeScale), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RollAmp, sizeof(m_RollAmp), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RollTimeScale, sizeof(m_RollTimeScale), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_PitchAmp, sizeof(m_PitchAmp), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_PitchTimeScale, sizeof(m_PitchTimeScale), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MaxBank, sizeof(m_MaxBank), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MaxBankTurnSpeed, sizeof(m_MaxBankTurnSpeed), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SpeedDampThresh, sizeof(m_SpeedDampThresh), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SpeedDamp, sizeof(m_SpeedDamp), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading TransportPhysics", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* TransportPhysicsRec::GetFilename() {
	return "DBFilesClient\\TransportPhysics.dbc";
}
