// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool WeaponImpactSoundsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_WeaponSubClassID, sizeof(m_WeaponSubClassID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ParrySoundType, sizeof(m_ParrySoundType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[0], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[1], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[2], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[3], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[4], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[5], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[6], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[7], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[8], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ImpactSoundID[9], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[0], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[1], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[2], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[3], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[4], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[5], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[6], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[7], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[8], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CritImpactSoundID[9], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading WeaponImpactSounds", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* WeaponImpactSoundsRec::GetFilename() {
	return "DBFilesClient\\WeaponImpactSounds.dbc";
}
