// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool WorldMapTransformsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MapID, sizeof(m_MapID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RegionMin[0], sizeof(m_RegionMin[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RegionMin[1], sizeof(m_RegionMin[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RegionMax[0], sizeof(m_RegionMax[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RegionMax[1], sizeof(m_RegionMax[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_NewMapID, sizeof(m_NewMapID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RegionOffset[0], sizeof(m_RegionOffset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RegionOffset[1], sizeof(m_RegionOffset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_NewDungeonMapID, sizeof(m_NewDungeonMapID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading WorldMapTransforms", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* WorldMapTransformsRec::GetFilename() {
	return "DBFilesClient\\WorldMapTransforms.dbc";
}
