// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool ZoneLightPointRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ZoneLightID, sizeof(m_ZoneLightID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Pos[0], sizeof(m_Pos[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Pos[1], sizeof(m_Pos[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_PointOrder, sizeof(m_PointOrder), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading ZoneLightPoint", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* ZoneLightPointRec::GetFilename() {
	return "DBFilesClient\\ZoneLightPoint.dbc";
}
