// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ACHIEVEMENT_REC_HPP
#define DB_REC_ACHIEVEMENT_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class AchievementRec {
    public:
        static constexpr uint32_t columnCount = 62;
        static constexpr uint32_t rowSize = 248;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_Faction;
        int32_t m_Instance_ID;
        int32_t m_Supercedes;
        const char* m_Title_lang;
        const char* m_Description_lang;
        int32_t m_Category;
        int32_t m_Points;
        int32_t m_Ui_order;
        int32_t m_Flags;
        int32_t m_IconID;
        const char* m_Reward_lang;
        int32_t m_Minimum_criteria;
        int32_t m_Shares_criteria;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif