// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ACHIEVEMENT_REC_HPP
#define DB_REC_ACHIEVEMENT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class AchievementRec {
    public:
        static constexpr uint32_t columnCount = 62;
        static constexpr uint32_t rowSize = 248;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_faction;
        int32_t m_instanceID;
        int32_t m_supercedes;
        const char* m_title;
        const char* m_description;
        int32_t m_category;
        int32_t m_points;
        int32_t m_uiOrder;
        int32_t m_flags;
        int32_t m_iconID;
        const char* m_reward;
        int32_t m_minimumCriteria;
        int32_t m_sharesCriteria;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif