// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ANIM_KIT_CONFIG_BONE_SET_REC_HPP
#define DB_REC_ANIM_KIT_CONFIG_BONE_SET_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class AnimKitConfigBoneSetRec {
    public:
        static constexpr uint32_t columnCount = 4;
        static constexpr uint32_t rowSize = 16;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_parentAnimKitConfigID;
        int32_t m_animKitBoneSetID;
        int32_t m_animKitPriorityID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif