// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ANIM_REPLACEMENT_SET_REC_HPP
#define DB_REC_ANIM_REPLACEMENT_SET_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class AnimReplacementSetRec {
    public:
        static constexpr uint32_t columnCount = 2;
        static constexpr uint32_t rowSize = 8;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_ExecOrder;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif