// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/AnimKitPriorityRec.hpp"

const char* AnimKitPriorityRec::GetFilename() {
    return "DBFilesClient\\AnimKitPriority.dbc";
}

bool AnimKitPriorityRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Priority, sizeof(this->m_Priority), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
