// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/AnimReplacementSetRec.hpp"

const char* AnimReplacementSetRec::GetFilename() {
    return "DBFilesClient\\AnimReplacementSet.dbc";
}

bool AnimReplacementSetRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ExecOrder, sizeof(this->m_ExecOrder), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
