// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/AnimKitConfigRec.hpp"
#include "util/SFile.hpp"

const char* AnimKitConfigRec::GetFilename() {
    return "DBFilesClient\\AnimKitConfig.dbc";
}

uint32_t AnimKitConfigRec::GetNumColumns() {
    return 2;
}

uint32_t AnimKitConfigRec::GetRowSize() {
    return 8;
}

bool AnimKitConfigRec::NeedIDAssigned() {
    return false;
}

int32_t AnimKitConfigRec::GetID() {
    return this->m_ID;
}

void AnimKitConfigRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool AnimKitConfigRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_configFlags, sizeof(this->m_configFlags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
