// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ANIM_KIT_BONE_SET_REC_HPP
#define DB_REC_ANIM_KIT_BONE_SET_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class AnimKitBoneSetRec {
    public:
        static constexpr uint32_t columnCount = 6;
        static constexpr uint32_t rowSize = 24;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        int32_t m_boneDataID;
        int32_t m_parentAnimKitBoneSetID;
        int32_t m_extraBoneCount;
        int32_t m_altAnimKitBoneSetID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif