// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_ANIMKITBONESETALIAS_REC_HPP
#define DB_ANIMKITBONESETALIAS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct AnimKitBoneSetAliasRec {
	static constexpr uint32_t columnCount = 3;
	static constexpr uint32_t rowSize = 12;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_BoneDataID;
	int32_t m_AnimKitBoneSetID;

	static const char* GetFilename() {
		return "DBFilesClient\\AnimKitBoneSetAlias.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_BoneDataID, sizeof(this->m_BoneDataID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AnimKitBoneSetID, sizeof(this->m_AnimKitBoneSetID), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif