// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ANIMATION_DATA_REC_HPP
#define DB_REC_ANIMATION_DATA_REC_HPP

#include <cstdint>

class SFile;

class AnimationDataRec {
    public:
        int32_t m_ID;
        const char* m_name;
        int32_t m_weaponflags;
        int32_t m_bodyflags;
        int32_t m_flags;
        int32_t m_fallback;
        int32_t m_behaviorID;
        int32_t m_behaviorTier;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif