// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ANIMATION_DATA_REC_HPP
#define DB_REC_ANIMATION_DATA_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class AnimationDataRec {
    public:
        static constexpr uint32_t columnCount = 8;
        static constexpr uint32_t rowSize = 32;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        int32_t m_weaponflags;
        int32_t m_bodyflags;
        int32_t m_flags;
        int32_t m_fallback;
        int32_t m_behaviorID;
        int32_t m_behaviorTier;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif