// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_AREA_GROUP_REC_HPP
#define DB_REC_AREA_GROUP_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class AreaGroupRec {
    public:
    static constexpr uint32_t columnCount = 8;
    static constexpr uint32_t rowSize = 32;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    int32_t m_AreaID[6];
    int32_t m_NextAreaID;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif