// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_AREATRIGGER_REC_HPP
#define DB_AREATRIGGER_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct AreaTriggerRec {
	static constexpr uint32_t columnCount = 10;
	static constexpr uint32_t rowSize = 40;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_ContinentID;
	float m_Pos[3];
	float m_Radius;
	float m_Box_length;
	float m_Box_width;
	float m_Box_height;
	float m_Box_yaw;

	static const char* GetFilename() {
		return "DBFilesClient\\AreaTrigger.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ContinentID, sizeof(this->m_ContinentID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Pos[0], sizeof(m_Pos[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Pos[1], sizeof(m_Pos[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Pos[2], sizeof(m_Pos[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Radius, sizeof(this->m_Radius), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Box_length, sizeof(this->m_Box_length), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Box_width, sizeof(this->m_Box_width), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Box_height, sizeof(this->m_Box_height), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Box_yaw, sizeof(this->m_Box_yaw), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif