// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/AreaAssignmentRec.hpp"

const char* AreaAssignmentRec::GetFilename() {
    return "DBFilesClient\\AreaAssignment.dbc";
}

int32_t AreaAssignmentRec::GetNumColumns() {
    return 5;
}

int32_t AreaAssignmentRec::GetRowSize() {
    return 20;
}

bool AreaAssignmentRec::NeedIDAssigned() {
    return false;
}

int32_t AreaAssignmentRec::GetID() {
    return this->m_ID;
}

void AreaAssignmentRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool AreaAssignmentRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_mapID, sizeof(this->m_mapID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_areaID, sizeof(this->m_areaID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_chunkX, sizeof(this->m_chunkX), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_chunkY, sizeof(this->m_chunkY), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
