// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_AREA_GROUP_REC_HPP
#define DB_REC_AREA_GROUP_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class AreaGroupRec {
    public:
        static constexpr uint32_t columnCount = 8;
        static constexpr uint32_t rowSize = 32;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_areaID[6];
        int32_t m_nextAreaID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif