// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/AreaTriggerRec.hpp"

const char* AreaTriggerRec::GetFilename() {
    return "DBFilesClient\\AreaTrigger.dbc";
}

bool AreaTriggerRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ContinentID, sizeof(this->m_ContinentID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Pos[0], sizeof(m_Pos[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Pos[1], sizeof(m_Pos[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Pos[2], sizeof(m_Pos[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Radius, sizeof(this->m_Radius), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Box_length, sizeof(this->m_Box_length), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Box_width, sizeof(this->m_Box_width), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Box_height, sizeof(this->m_Box_height), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Box_yaw, sizeof(this->m_Box_yaw), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
