// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/AreaAssignmentRec.hpp"

const char* AreaAssignmentRec::GetFilename() {
    return "DBFilesClient\\AreaAssignment.dbc";
}

bool AreaAssignmentRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_MapID, sizeof(this->m_MapID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_AreaID, sizeof(this->m_AreaID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ChunkX, sizeof(this->m_ChunkX), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ChunkY, sizeof(this->m_ChunkY), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
