// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ArmorLocationRec.hpp"

const char* ArmorLocationRec::GetFilename() {
    return "DBFilesClient\\ArmorLocation.dbc";
}

int32_t ArmorLocationRec::GetID() {
    return this->m_ID;
}

bool ArmorLocationRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_clothmodifier, sizeof(this->m_clothmodifier), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_leathermodifier, sizeof(this->m_leathermodifier), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_chainmodifier, sizeof(this->m_chainmodifier), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_platemodifier, sizeof(this->m_platemodifier), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_modifier, sizeof(this->m_modifier), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
