// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ARMOR_LOCATION_REC_HPP
#define DB_REC_ARMOR_LOCATION_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class ArmorLocationRec {
    public:
    static constexpr uint32_t columnCount = 6;
    static constexpr uint32_t rowSize = 24;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    float m_Clothmodifier;
    float m_Leathermodifier;
    float m_Chainmodifier;
    float m_Platemodifier;
    float m_Modifier;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif