// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ATTACK_ANIM_TYPES_REC_HPP
#define DB_REC_ATTACK_ANIM_TYPES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class AttackAnimTypesRec {
    public:
        static constexpr uint32_t columnCount = 2;
        static constexpr uint32_t rowSize = 8;
        static constexpr bool indexIsID = true;

        int32_t m_animID;
        const char* m_animName;
        int32_t m_generatedID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif