// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ATTACK_ANIM_KITS_REC_HPP
#define DB_REC_ATTACK_ANIM_KITS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class AttackAnimKitsRec {
    public:
        static constexpr uint32_t columnCount = 5;
        static constexpr uint32_t rowSize = 20;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_ItemSubclassID;
        int32_t m_AnimTypeID;
        int32_t m_AnimFrequency;
        int32_t m_WhichHand;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif