// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/BankBagSlotPricesRec.hpp"
#include "util/SFile.hpp"

const char* BankBagSlotPricesRec::GetFilename() {
    return "DBFilesClient\\BankBagSlotPrices.dbc";
}

uint32_t BankBagSlotPricesRec::GetNumColumns() {
    return 2;
}

uint32_t BankBagSlotPricesRec::GetRowSize() {
    return 8;
}

bool BankBagSlotPricesRec::NeedIDAssigned() {
    return false;
}

int32_t BankBagSlotPricesRec::GetID() {
    return this->m_ID;
}

void BankBagSlotPricesRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool BankBagSlotPricesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_cost, sizeof(this->m_cost), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
