// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_CAMERAMODE_REC_HPP
#define DB_CAMERAMODE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct CameraModeRec {
	static constexpr uint32_t columnCount = 17;
	static constexpr uint32_t rowSize = 68;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_Name;
	int32_t m_Type;
	int32_t m_Flags;
	float m_PositionOffset[3];
	float m_TargetOffset[3];
	float m_PositionSmoothing;
	float m_RotationSmoothing;
	float m_FieldOfView;
	int32_t m_LockedPositionOffsetBase;
	int32_t m_LockedPositionOffsetDirection;
	int32_t m_LockedTargetOffsetBase;
	int32_t m_LockedTargetOffsetDirection;

	static const char* GetFilename() {
		return "DBFilesClient\\CameraMode.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t NameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Type, sizeof(this->m_Type), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PositionOffset[0], sizeof(m_PositionOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PositionOffset[1], sizeof(m_PositionOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PositionOffset[2], sizeof(m_PositionOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TargetOffset[0], sizeof(m_TargetOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TargetOffset[1], sizeof(m_TargetOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TargetOffset[2], sizeof(m_TargetOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PositionSmoothing, sizeof(this->m_PositionSmoothing), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RotationSmoothing, sizeof(this->m_RotationSmoothing), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_FieldOfView, sizeof(this->m_FieldOfView), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_LockedPositionOffsetBase, sizeof(this->m_LockedPositionOffsetBase), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_LockedPositionOffsetDirection, sizeof(this->m_LockedPositionOffsetDirection), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_LockedTargetOffsetBase, sizeof(this->m_LockedTargetOffsetBase), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_LockedTargetOffsetDirection, sizeof(this->m_LockedTargetOffsetDirection), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Name = &stringBuffer[NameOfs];
		} else {
			this->m_Name = "";
		}

		return true;
	}
};

#endif