// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CFG_CONFIGS_REC_HPP
#define DB_REC_CFG_CONFIGS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class Cfg_ConfigsRec {
    public:
        int32_t m_ID;
        int32_t m_realmType;
        int32_t m_playerKillingAllowed;
        int32_t m_roleplaying;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif