// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAR_VARIATIONS_REC_HPP
#define DB_REC_CHAR_VARIATIONS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class CharVariationsRec {
    public:
        static constexpr uint32_t columnCount = 6;
        static constexpr uint32_t rowSize = 24;
        static constexpr bool indexIsID = true;

        int32_t m_RaceID;
        int32_t m_SexID;
        int32_t m_TextureHoldLayer[4];

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif