// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_CHARSECTIONS_REC_HPP
#define DB_CHARSECTIONS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct CharSectionsRec {
	static constexpr uint32_t columnCount = 10;
	static constexpr uint32_t rowSize = 40;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_RaceID;
	int32_t m_SexID;
	int32_t m_BaseSection;
	const char* m_TextureName[3];
	int32_t m_Flags;
	int32_t m_VariationIndex;
	int32_t m_ColorIndex;

	static const char* GetFilename() {
		return "DBFilesClient\\CharSections.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t TextureNameOfs[3];

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RaceID, sizeof(this->m_RaceID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SexID, sizeof(this->m_SexID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_BaseSection, sizeof(this->m_BaseSection), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &TextureNameOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &TextureNameOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &TextureNameOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VariationIndex, sizeof(this->m_VariationIndex), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ColorIndex, sizeof(this->m_ColorIndex), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_TextureName[0] = &stringBuffer[TextureNameOfs[0]];
			this->m_TextureName[1] = &stringBuffer[TextureNameOfs[1]];
			this->m_TextureName[2] = &stringBuffer[TextureNameOfs[2]];
		} else {
			this->m_TextureName[0] = "";
			this->m_TextureName[1] = "";
			this->m_TextureName[2] = "";
		}

		return true;
	}
};

#endif