// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAR_SECTIONS_REC_HPP
#define DB_REC_CHAR_SECTIONS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class CharSectionsRec {
    public:
        static constexpr uint32_t columnCount = 10;
        static constexpr uint32_t rowSize = 40;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_RaceID;
        int32_t m_SexID;
        int32_t m_BaseSection;
        const char* m_TextureName[3];
        int32_t m_Flags;
        int32_t m_VariationIndex;
        int32_t m_ColorIndex;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif