// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAR_TITLES_REC_HPP
#define DB_REC_CHAR_TITLES_REC_HPP

#include <cstdint>

class SFile;

class CharTitlesRec {
    public:
        int32_t m_ID;
        int32_t m_conditionID;
        const char* m_name;
        const char* m_name1;
        int32_t m_maskID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif