// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAR_HAIR_GEOSETS_REC_HPP
#define DB_REC_CHAR_HAIR_GEOSETS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class CharHairGeosetsRec {
    public:
        static constexpr uint32_t columnCount = 6;
        static constexpr uint32_t rowSize = 24;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_raceID;
        int32_t m_sexID;
        int32_t m_variationID;
        int32_t m_geosetID;
        int32_t m_showscalp;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif