// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHARACTER_FACIAL_HAIR_STYLES_REC_HPP
#define DB_REC_CHARACTER_FACIAL_HAIR_STYLES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class CharacterFacialHairStylesRec {
    public:
        static constexpr uint32_t columnCount = 8;
        static constexpr uint32_t rowSize = 32;
        static constexpr bool indexIsID = true;

        int32_t m_raceID;
        int32_t m_sexID;
        int32_t m_variationID;
        int32_t m_geoset[5];
        int32_t m_generatedID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif