// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAT_PROFANITY_REC_HPP
#define DB_REC_CHAT_PROFANITY_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ChatProfanityRec {
    public:
        int32_t m_ID;
        const char* m_text;
        int32_t m_language;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif