// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHAT_CHANNELS_REC_HPP
#define DB_REC_CHAT_CHANNELS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class ChatChannelsRec {
    public:
        static constexpr uint32_t columnCount = 37;
        static constexpr uint32_t rowSize = 148;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_Flags;
        int32_t m_FactionGroup;
        const char* m_Name_lang;
        const char* m_Shortcut_lang;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif