// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CHR_CLASSES_REC_HPP
#define DB_REC_CHR_CLASSES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ChrClassesRec {
    public:
        static constexpr uint32_t columnCount = 60;
        static constexpr uint32_t rowSize = 240;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_damageBonusStat;
        int32_t m_displayPower;
        const char* m_petNameToken;
        const char* m_name;
        const char* m_nameFemale;
        const char* m_nameMale;
        const char* m_filename;
        int32_t m_spellClassSet;
        int32_t m_flags;
        int32_t m_cinematicSequenceID;
        int32_t m_requiredExpansion;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif