// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/CreatureSpellDataRec.hpp"

const char* CreatureSpellDataRec::GetFilename() {
    return "DBFilesClient\\CreatureSpellData.dbc";
}

int32_t CreatureSpellDataRec::GetNumColumns() {
    return 9;
}

int32_t CreatureSpellDataRec::GetRowSize() {
    return 36;
}

bool CreatureSpellDataRec::NeedIDAssigned() {
    return false;
}

int32_t CreatureSpellDataRec::GetID() {
    return this->m_ID;
}

void CreatureSpellDataRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool CreatureSpellDataRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spells[0], sizeof(m_spells[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spells[1], sizeof(m_spells[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spells[2], sizeof(m_spells[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spells[3], sizeof(m_spells[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_availability[0], sizeof(m_availability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_availability[1], sizeof(m_availability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_availability[2], sizeof(m_availability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_availability[3], sizeof(m_availability[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
