// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_CREATURE_DISPLAY_INFO_EXTRA_REC_HPP
#define DB_REC_CREATURE_DISPLAY_INFO_EXTRA_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class CreatureDisplayInfoExtraRec {
    public:
        static constexpr uint32_t columnCount = 21;
        static constexpr uint32_t rowSize = 84;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_displayRaceID;
        int32_t m_displaySexID;
        int32_t m_skinID;
        int32_t m_faceID;
        int32_t m_hairStyleID;
        int32_t m_hairColorID;
        int32_t m_facialHairID;
        int32_t m_npcitemDisplay[11];
        int32_t m_flags;
        const char* m_bakeName;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif