// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/CreatureMovementInfoRec.hpp"

const char* CreatureMovementInfoRec::GetFilename() {
    return "DBFilesClient\\CreatureMovementInfo.dbc";
}

int32_t CreatureMovementInfoRec::GetNumColumns() {
    return 2;
}

int32_t CreatureMovementInfoRec::GetRowSize() {
    return 8;
}

bool CreatureMovementInfoRec::NeedIDAssigned() {
    return false;
}

int32_t CreatureMovementInfoRec::GetID() {
    return this->m_ID;
}

void CreatureMovementInfoRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool CreatureMovementInfoRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_smoothFacingChaseRate, sizeof(this->m_smoothFacingChaseRate), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
