// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_CREATURESOUNDDATA_REC_HPP
#define DB_CREATURESOUNDDATA_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct CreatureSoundDataRec {
	static constexpr uint32_t columnCount = 38;
	static constexpr uint32_t rowSize = 152;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_SoundExertionID;
	int32_t m_SoundExertionCriticalID;
	int32_t m_SoundInjuryID;
	int32_t m_SoundInjuryCriticalID;
	int32_t m_SoundInjuryCrushingBlowID;
	int32_t m_SoundDeathID;
	int32_t m_SoundStunID;
	int32_t m_SoundStandID;
	int32_t m_SoundFootstepID;
	int32_t m_SoundAggroID;
	int32_t m_SoundWingFlapID;
	int32_t m_SoundWingGlideID;
	int32_t m_SoundAlertID;
	int32_t m_SoundFidget[5];
	int32_t m_CustomAttack[4];
	int32_t m_NPCSoundID;
	int32_t m_LoopSoundID;
	int32_t m_CreatureImpactType;
	int32_t m_SoundJumpStartID;
	int32_t m_SoundJumpEndID;
	int32_t m_SoundPetAttackID;
	int32_t m_SoundPetOrderID;
	int32_t m_SoundPetDismissID;
	float m_FidgetDelaySecondsMin;
	float m_FidgetDelaySecondsMax;
	int32_t m_BirthSoundID;
	int32_t m_SpellCastDirectedSoundID;
	int32_t m_SubmergeSoundID;
	int32_t m_SubmergedSoundID;
	int32_t m_CreatureSoundDataIDPet;

	static const char* GetFilename() {
		return "DBFilesClient\\CreatureSoundData.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundExertionID, sizeof(this->m_SoundExertionID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundExertionCriticalID, sizeof(this->m_SoundExertionCriticalID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundInjuryID, sizeof(this->m_SoundInjuryID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundInjuryCriticalID, sizeof(this->m_SoundInjuryCriticalID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundInjuryCrushingBlowID, sizeof(this->m_SoundInjuryCrushingBlowID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundDeathID, sizeof(this->m_SoundDeathID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundStunID, sizeof(this->m_SoundStunID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundStandID, sizeof(this->m_SoundStandID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundFootstepID, sizeof(this->m_SoundFootstepID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundAggroID, sizeof(this->m_SoundAggroID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundWingFlapID, sizeof(this->m_SoundWingFlapID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundWingGlideID, sizeof(this->m_SoundWingGlideID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundAlertID, sizeof(this->m_SoundAlertID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundFidget[0], sizeof(m_SoundFidget[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundFidget[1], sizeof(m_SoundFidget[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundFidget[2], sizeof(m_SoundFidget[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundFidget[3], sizeof(m_SoundFidget[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundFidget[4], sizeof(m_SoundFidget[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CustomAttack[0], sizeof(m_CustomAttack[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CustomAttack[1], sizeof(m_CustomAttack[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CustomAttack[2], sizeof(m_CustomAttack[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CustomAttack[3], sizeof(m_CustomAttack[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_NPCSoundID, sizeof(this->m_NPCSoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_LoopSoundID, sizeof(this->m_LoopSoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CreatureImpactType, sizeof(this->m_CreatureImpactType), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundJumpStartID, sizeof(this->m_SoundJumpStartID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundJumpEndID, sizeof(this->m_SoundJumpEndID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundPetAttackID, sizeof(this->m_SoundPetAttackID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundPetOrderID, sizeof(this->m_SoundPetOrderID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundPetDismissID, sizeof(this->m_SoundPetDismissID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_FidgetDelaySecondsMin, sizeof(this->m_FidgetDelaySecondsMin), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_FidgetDelaySecondsMax, sizeof(this->m_FidgetDelaySecondsMax), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_BirthSoundID, sizeof(this->m_BirthSoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SpellCastDirectedSoundID, sizeof(this->m_SpellCastDirectedSoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SubmergeSoundID, sizeof(this->m_SubmergeSoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SubmergedSoundID, sizeof(this->m_SubmergedSoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CreatureSoundDataIDPet, sizeof(this->m_CreatureSoundDataIDPet), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif