// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/CurrencyTypesRec.hpp"

const char* CurrencyTypesRec::GetFilename() {
    return "DBFilesClient\\CurrencyTypes.dbc";
}

int32_t CurrencyTypesRec::GetNumColumns() {
    return 4;
}

int32_t CurrencyTypesRec::GetRowSize() {
    return 16;
}

bool CurrencyTypesRec::NeedIDAssigned() {
    return false;
}

int32_t CurrencyTypesRec::GetID() {
    return this->m_ID;
}

void CurrencyTypesRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool CurrencyTypesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID, sizeof(this->m_itemID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_categoryID, sizeof(this->m_categoryID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bitIndex, sizeof(this->m_bitIndex), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
