// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/DanceMovesRec.hpp"

const char* DanceMovesRec::GetFilename() {
    return "DBFilesClient\\DanceMoves.dbc";
}

bool DanceMovesRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t Internal_nameOfs;
    uint32_t Name_langOfs[16];
    uint32_t Name_langMask;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Type, sizeof(this->m_Type), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Param, sizeof(this->m_Param), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Fallback, sizeof(this->m_Fallback), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Racemask, sizeof(this->m_Racemask), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Internal_nameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &Name_langMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_LockID, sizeof(this->m_LockID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Internal_name = &stringBuffer[Internal_nameOfs];
        this->m_Name_lang = &stringBuffer[Name_langOfs[CURRENT_LANGUAGE]];
    } else {
        this->m_Internal_name = "";
        this->m_Name_lang = "";
    }

    return true;
}
