// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_DANCE_MOVES_REC_HPP
#define DB_REC_DANCE_MOVES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class DanceMovesRec {
    public:
        static constexpr uint32_t columnCount = 24;
        static constexpr uint32_t rowSize = 96;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_type;
        int32_t m_param;
        int32_t m_fallback;
        int32_t m_racemask;
        const char* m_internalName;
        const char* m_name;
        int32_t m_lockID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif