// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/DeathThudLookupsRec.hpp"
#include "util/SFile.hpp"

const char* DeathThudLookupsRec::GetFilename() {
    return "DBFilesClient\\DeathThudLookups.dbc";
}

uint32_t DeathThudLookupsRec::GetNumColumns() {
    return 5;
}

uint32_t DeathThudLookupsRec::GetRowSize() {
    return 20;
}

bool DeathThudLookupsRec::NeedIDAssigned() {
    return false;
}

int32_t DeathThudLookupsRec::GetID() {
    return this->m_ID;
}

void DeathThudLookupsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool DeathThudLookupsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_sizeClass, sizeof(this->m_sizeClass), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_terrainTypeSoundID, sizeof(this->m_terrainTypeSoundID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_soundEntryID, sizeof(this->m_soundEntryID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_soundEntryIdwater, sizeof(this->m_soundEntryIdwater), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
