// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_DUNGEON_MAP_REC_HPP
#define DB_REC_DUNGEON_MAP_REC_HPP

#include <cstdint>

class SFile;

class DungeonMapRec {
    public:
        int32_t m_ID;
        int32_t m_mapID;
        int32_t m_floorIndex;
        float m_minX;
        float m_maxX;
        float m_minY;
        float m_maxY;
        int32_t m_parentWorldMapID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif