// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_DUNGEON_MAP_REC_HPP
#define DB_REC_DUNGEON_MAP_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class DungeonMapRec {
    public:
        static constexpr uint32_t columnCount = 8;
        static constexpr uint32_t rowSize = 32;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_mapID;
        int32_t m_floorIndex;
        float m_minX;
        float m_maxX;
        float m_minY;
        float m_maxY;
        int32_t m_parentWorldMapID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif