// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/DurabilityQualityRec.hpp"

const char* DurabilityQualityRec::GetFilename() {
    return "DBFilesClient\\DurabilityQuality.dbc";
}

bool DurabilityQualityRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Data, sizeof(this->m_Data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
