// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/EmotesRec.hpp"
#include "util/SFile.hpp"

const char* EmotesRec::GetFilename() {
    return "DBFilesClient\\Emotes.dbc";
}

uint32_t EmotesRec::GetNumColumns() {
    return 7;
}

uint32_t EmotesRec::GetRowSize() {
    return 28;
}

bool EmotesRec::NeedIDAssigned() {
    return false;
}

int32_t EmotesRec::GetID() {
    return this->m_ID;
}

void EmotesRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool EmotesRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t emoteSlashCommandOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &emoteSlashCommandOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_animID, sizeof(this->m_animID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteFlags, sizeof(this->m_emoteFlags), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteSpecProc, sizeof(this->m_emoteSpecProc), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteSpecProcParam, sizeof(this->m_emoteSpecProcParam), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eventSoundID, sizeof(this->m_eventSoundID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_emoteSlashCommand = &stringBuffer[emoteSlashCommandOfs];
    } else {
        this->m_emoteSlashCommand = "";
    }

    return true;
}
