// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_EMOTES_REC_HPP
#define DB_REC_EMOTES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class EmotesRec {
    public:
        static constexpr uint32_t columnCount = 7;
        static constexpr uint32_t rowSize = 28;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_emoteSlashCommand;
        int32_t m_animID;
        int32_t m_emoteFlags;
        int32_t m_emoteSpecProc;
        int32_t m_emoteSpecProcParam;
        int32_t m_eventSoundID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif