// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_EMOTES_REC_HPP
#define DB_REC_EMOTES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class EmotesRec {
    public:
        int32_t m_ID;
        const char* m_emoteSlashCommand;
        int32_t m_animID;
        int32_t m_emoteFlags;
        int32_t m_emoteSpecProc;
        int32_t m_emoteSpecProcParam;
        int32_t m_eventSoundID;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif