// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/EmotesTextRec.hpp"
#include "util/SFile.hpp"

const char* EmotesTextRec::GetFilename() {
    return "DBFilesClient\\EmotesText.dbc";
}

uint32_t EmotesTextRec::GetNumColumns() {
    return 19;
}

uint32_t EmotesTextRec::GetRowSize() {
    return 76;
}

bool EmotesTextRec::NeedIDAssigned() {
    return false;
}

int32_t EmotesTextRec::GetID() {
    return this->m_ID;
}

void EmotesTextRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool EmotesTextRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t nameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteID, sizeof(this->m_emoteID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[0], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[1], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[2], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[3], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[4], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[5], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[6], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[7], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[8], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[9], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[10], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[11], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[12], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[13], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[14], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_emoteText[15], sizeof(m_emoteText[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_name = &stringBuffer[nameOfs];
    } else {
        this->m_name = "";
    }

    return true;
}
