// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/EmotesTextRec.hpp"

const char* EmotesTextRec::GetFilename() {
    return "DBFilesClient\\EmotesText.dbc";
}

bool EmotesTextRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t NameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteID, sizeof(this->m_EmoteID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[0], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[1], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[2], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[3], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[4], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[5], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[6], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[7], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[8], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[9], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[10], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[11], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[12], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[13], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[14], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EmoteText[15], sizeof(m_EmoteText[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Name = &stringBuffer[NameOfs];
    } else {
        this->m_Name = "";
    }

    return true;
}
