// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_EMOTES_TEXT_REC_HPP
#define DB_REC_EMOTES_TEXT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class EmotesTextRec {
    public:
        static constexpr uint32_t columnCount = 19;
        static constexpr uint32_t rowSize = 76;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        int32_t m_emoteID;
        int32_t m_emoteText[16];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif