// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_FACTION_REC_HPP
#define DB_REC_FACTION_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class FactionRec {
    public:
        int32_t m_ID;
        int32_t m_reputationIndex;
        int32_t m_reputationRaceMask[4];
        int32_t m_reputationClassMask[4];
        int32_t m_reputationBase[4];
        int32_t m_reputationFlags[4];
        int32_t m_parentFactionID;
        float m_parentFactionMod[2];
        int32_t m_parentFactionCap[2];
        const char* m_name;
        const char* m_description;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif