// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_FOOTPRINT_TEXTURES_REC_HPP
#define DB_REC_FOOTPRINT_TEXTURES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class FootprintTexturesRec {
    public:
        static constexpr uint32_t columnCount = 2;
        static constexpr uint32_t rowSize = 8;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_footstepFilename;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif