// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_FOOTSTEP_TERRAIN_LOOKUP_REC_HPP
#define DB_REC_FOOTSTEP_TERRAIN_LOOKUP_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class FootstepTerrainLookupRec {
    public:
        static constexpr uint32_t columnCount = 5;
        static constexpr uint32_t rowSize = 20;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_creatureFootstepID;
        int32_t m_terrainSoundID;
        int32_t m_soundID;
        int32_t m_soundIdsplash;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif