// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_GAME_OBJECT_ART_KIT_REC_HPP
#define DB_REC_GAME_OBJECT_ART_KIT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class GameObjectArtKitRec {
    public:
        int32_t m_ID;
        const char* m_textureVariation[3];
        const char* m_attachModel[4];

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif