// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_GAME_OBJECT_DISPLAY_INFO_REC_HPP
#define DB_REC_GAME_OBJECT_DISPLAY_INFO_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class GameObjectDisplayInfoRec {
    public:
        static constexpr uint32_t columnCount = 19;
        static constexpr uint32_t rowSize = 76;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_ModelName;
        int32_t m_Sound[10];
        float m_GeoBoxMin[3];
        float m_GeoBoxMax[3];
        int32_t m_ObjectEffectPackageID;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif