// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_GAME_TABLES_REC_HPP
#define DB_REC_GAME_TABLES_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class GameTablesRec {
    public:
        static constexpr uint32_t columnCount = 3;
        static constexpr uint32_t rowSize = 12;
        static constexpr bool indexIsID = true;

        const char* m_Name;
        int32_t m_NumRows;
        int32_t m_NumColumns;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif