// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GemPropertiesRec.hpp"

const char* GemPropertiesRec::GetFilename() {
    return "DBFilesClient\\GemProperties.dbc";
}

bool GemPropertiesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Enchant_ID, sizeof(this->m_Enchant_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Maxcount_inv, sizeof(this->m_Maxcount_inv), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Maxcount_item, sizeof(this->m_Maxcount_item), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Type, sizeof(this->m_Type), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
