// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_GLYPHSLOT_REC_HPP
#define DB_GLYPHSLOT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct GlyphSlotRec {
	static constexpr uint32_t columnCount = 3;
	static constexpr uint32_t rowSize = 12;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_Type;
	int32_t m_Tooltip;

	static const char* GetFilename() {
		return "DBFilesClient\\GlyphSlot.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Type, sizeof(this->m_Type), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Tooltip, sizeof(this->m_Tooltip), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif