// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GMSurveySurveysRec.hpp"
#include "util/SFile.hpp"

const char* GMSurveySurveysRec::GetFilename() {
    return "DBFilesClient\\GMSurveySurveys.dbc";
}

uint32_t GMSurveySurveysRec::GetNumColumns() {
    return 11;
}

uint32_t GMSurveySurveysRec::GetRowSize() {
    return 44;
}

bool GMSurveySurveysRec::NeedIDAssigned() {
    return false;
}

int32_t GMSurveySurveysRec::GetID() {
    return this->m_ID;
}

void GMSurveySurveysRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool GMSurveySurveysRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[0], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[1], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[2], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[3], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[4], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[5], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[6], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[7], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[8], sizeof(m_[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_[9], sizeof(m_[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
