// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GMSurveyCurrentSurveyRec.hpp"

const char* GMSurveyCurrentSurveyRec::GetFilename() {
    return "DBFilesClient\\GMSurveyCurrentSurvey.dbc";
}

int32_t GMSurveyCurrentSurveyRec::GetID() {
    return this->m_generatedID;
}

bool GMSurveyCurrentSurveyRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_langid, sizeof(this->m_langid), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_gmsurveyID, sizeof(this->m_gmsurveyID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
