// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GMSurveyQuestionsRec.hpp"

const char* GMSurveyQuestionsRec::GetFilename() {
    return "DBFilesClient\\GMSurveyQuestions.dbc";
}

int32_t GMSurveyQuestionsRec::GetNumColumns() {
    return 18;
}

int32_t GMSurveyQuestionsRec::GetRowSize() {
    return 72;
}

bool GMSurveyQuestionsRec::NeedIDAssigned() {
    return false;
}

int32_t GMSurveyQuestionsRec::GetID() {
    return this->m_ID;
}

void GMSurveyQuestionsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool GMSurveyQuestionsRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t questionOfs[16];
    uint32_t questionMask;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &questionMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_question = &stringBuffer[questionOfs[CURRENT_LANGUAGE]];
    } else {
        this->m_question = "";
    }

    return true;
}
