// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_GMSURVEY_CURRENT_SURVEY_REC_HPP
#define DB_REC_GMSURVEY_CURRENT_SURVEY_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class GMSurveyCurrentSurveyRec {
    public:
        int32_t m_langid;
        int32_t m_gmsurveyID;
        int32_t m_generatedID;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif