// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GMTicketCategoryRec.hpp"

const char* GMTicketCategoryRec::GetFilename() {
    return "DBFilesClient\\GMTicketCategory.dbc";
}

int32_t GMTicketCategoryRec::GetNumColumns() {
    return 18;
}

int32_t GMTicketCategoryRec::GetRowSize() {
    return 72;
}

bool GMTicketCategoryRec::NeedIDAssigned() {
    return false;
}

int32_t GMTicketCategoryRec::GetID() {
    return this->m_ID;
}

void GMTicketCategoryRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool GMTicketCategoryRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t categoryOfs[16];
    uint32_t categoryMask;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &categoryMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_category = &stringBuffer[categoryOfs[CURRENT_LANGUAGE]];
    } else {
        this->m_category = "";
    }

    return true;
}
