// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GroundEffectDoodadRec.hpp"

const char* GroundEffectDoodadRec::GetFilename() {
    return "DBFilesClient\\GroundEffectDoodad.dbc";
}

bool GroundEffectDoodadRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t DoodadpathOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &DoodadpathOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Doodadpath = &stringBuffer[DoodadpathOfs];
    } else {
        this->m_Doodadpath = "";
    }

    return true;
}
