// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_GROUNDEFFECTDOODAD_REC_HPP
#define DB_GROUNDEFFECTDOODAD_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct GroundEffectDoodadRec {
	static constexpr uint32_t columnCount = 3;
	static constexpr uint32_t rowSize = 12;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_Doodadpath;
	int32_t m_Flags;

	static const char* GetFilename() {
		return "DBFilesClient\\GroundEffectDoodad.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t DoodadpathOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DoodadpathOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Doodadpath = &stringBuffer[DoodadpathOfs];
		} else {
			this->m_Doodadpath = "";
		}

		return true;
	}
};

#endif