// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_GROUNDEFFECTTEXTURE_REC_HPP
#define DB_GROUNDEFFECTTEXTURE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct GroundEffectTextureRec {
	static constexpr uint32_t columnCount = 11;
	static constexpr uint32_t rowSize = 44;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_DoodadID[4];
	int32_t m_DoodadWeight[4];
	int32_t m_Density;
	int32_t m_Sound;

	static const char* GetFilename() {
		return "DBFilesClient\\GroundEffectTexture.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadID[0], sizeof(m_DoodadID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadID[1], sizeof(m_DoodadID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadID[2], sizeof(m_DoodadID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadID[3], sizeof(m_DoodadID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadWeight[0], sizeof(m_DoodadWeight[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadWeight[1], sizeof(m_DoodadWeight[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadWeight[2], sizeof(m_DoodadWeight[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DoodadWeight[3], sizeof(m_DoodadWeight[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Density, sizeof(this->m_Density), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Sound, sizeof(this->m_Sound), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif