// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtBarberShopCostBaseRec.hpp"

const char* gtBarberShopCostBaseRec::GetFilename() {
    return "DBFilesClient\\gtBarberShopCostBase.dbc";
}

bool gtBarberShopCostBaseRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_Data, sizeof(this->m_Data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
