// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtChanceToMeleeCritRec.hpp"

const char* gtChanceToMeleeCritRec::GetFilename() {
    return "DBFilesClient\\gtChanceToMeleeCrit.dbc";
}

bool gtChanceToMeleeCritRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_Data, sizeof(this->m_Data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
