// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtChanceToSpellCritBaseRec.hpp"

const char* gtChanceToSpellCritBaseRec::GetFilename() {
    return "DBFilesClient\\gtChanceToSpellCritBase.dbc";
}

bool gtChanceToSpellCritBaseRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_Data, sizeof(this->m_Data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
