// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtChanceToMeleeCritBaseRec.hpp"

const char* gtChanceToMeleeCritBaseRec::GetFilename() {
    return "DBFilesClient\\gtChanceToMeleeCritBase.dbc";
}

bool gtChanceToMeleeCritBaseRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_Data, sizeof(this->m_Data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
