// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtCombatRatingsRec.hpp"
#include "util/SFile.hpp"

const char* gtCombatRatingsRec::GetFilename() {
    return "DBFilesClient\\gtCombatRatings.dbc";
}

uint32_t gtCombatRatingsRec::GetNumColumns() {
    return 1;
}

uint32_t gtCombatRatingsRec::GetRowSize() {
    return 4;
}

bool gtCombatRatingsRec::NeedIDAssigned() {
    return true;
}

int32_t gtCombatRatingsRec::GetID() {
    return this->m_generatedID;
}

void gtCombatRatingsRec::SetID(int32_t id) {
    this->m_generatedID = id;
}

bool gtCombatRatingsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_data, sizeof(this->m_data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
