// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_GT_NPCMANA_COST_SCALER_REC_HPP
#define DB_REC_GT_NPCMANA_COST_SCALER_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class gtNPCManaCostScalerRec {
    public:
    static constexpr uint32_t columnCount = 1;
    static constexpr uint32_t rowSize = 4;
    static constexpr bool indexIsID = true;

    float m_Data;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif