// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtOCTRegenMPRec.hpp"

const char* gtOCTRegenMPRec::GetFilename() {
    return "DBFilesClient\\gtOCTRegenMP.dbc";
}

int32_t gtOCTRegenMPRec::GetID() {
    return this->m_generatedID;
}

bool gtOCTRegenMPRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_data, sizeof(this->m_data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
