// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtRegenHPPerSptRec.hpp"

const char* gtRegenHPPerSptRec::GetFilename() {
    return "DBFilesClient\\gtRegenHPPerSpt.dbc";
}

bool gtRegenHPPerSptRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_Data, sizeof(this->m_Data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
