// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/gtRegenMPPerSptRec.hpp"
#include "util/SFile.hpp"

const char* gtRegenMPPerSptRec::GetFilename() {
    return "DBFilesClient\\gtRegenMPPerSpt.dbc";
}

uint32_t gtRegenMPPerSptRec::GetNumColumns() {
    return 1;
}

uint32_t gtRegenMPPerSptRec::GetRowSize() {
    return 4;
}

bool gtRegenMPPerSptRec::NeedIDAssigned() {
    return true;
}

int32_t gtRegenMPPerSptRec::GetID() {
    return this->m_generatedID;
}

void gtRegenMPPerSptRec::SetID(int32_t id) {
    this->m_generatedID = id;
}

bool gtRegenMPPerSptRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_data, sizeof(this->m_data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
