// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_GUILD_PERK_SPELLS_REC_HPP
#define DB_REC_GUILD_PERK_SPELLS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class GuildPerkSpellsRec {
    public:
        static constexpr uint32_t columnCount = 3;
        static constexpr uint32_t rowSize = 12;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_GuildLevel;
        int32_t m_SpellID;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif