// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/GuildPerkSpellsRec.hpp"

const char* GuildPerkSpellsRec::GetFilename() {
    return "DBFilesClient\\GuildPerkSpells.dbc";
}

int32_t GuildPerkSpellsRec::GetNumColumns() {
    return 3;
}

int32_t GuildPerkSpellsRec::GetRowSize() {
    return 12;
}

bool GuildPerkSpellsRec::NeedIDAssigned() {
    return false;
}

int32_t GuildPerkSpellsRec::GetID() {
    return this->m_ID;
}

void GuildPerkSpellsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool GuildPerkSpellsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_guildLevel, sizeof(this->m_guildLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spellID, sizeof(this->m_spellID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
