// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/HelmetGeosetVisDataRec.hpp"
#include "util/SFile.hpp"

const char* HelmetGeosetVisDataRec::GetFilename() {
    return "DBFilesClient\\HelmetGeosetVisData.dbc";
}

uint32_t HelmetGeosetVisDataRec::GetNumColumns() {
    return 8;
}

uint32_t HelmetGeosetVisDataRec::GetRowSize() {
    return 32;
}

bool HelmetGeosetVisDataRec::NeedIDAssigned() {
    return false;
}

int32_t HelmetGeosetVisDataRec::GetID() {
    return this->m_ID;
}

void HelmetGeosetVisDataRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool HelmetGeosetVisDataRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[0], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[1], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[2], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[3], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[4], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[5], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hideGeoset[6], sizeof(m_hideGeoset[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
