// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/HolidaysRec.hpp"

const char* HolidaysRec::GetFilename() {
    return "DBFilesClient\\Holidays.dbc";
}

int32_t HolidaysRec::GetID() {
    return this->m_ID;
}

bool HolidaysRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t textureFileNameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[0], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[1], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[2], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[3], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[4], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[5], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[6], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[7], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[8], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_duration[9], sizeof(m_duration[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[0], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[1], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[2], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[3], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[4], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[5], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[6], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[7], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[8], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[9], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[10], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[11], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[12], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[13], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[14], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[15], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[16], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[17], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[18], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[19], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[20], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[21], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[22], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[23], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[24], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_date[25], sizeof(m_date[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_region, sizeof(this->m_region), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_looping, sizeof(this->m_looping), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[0], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[1], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[2], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[3], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[4], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[5], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[6], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[7], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[8], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFlags[9], sizeof(m_calendarFlags[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_holidayNameID, sizeof(this->m_holidayNameID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_holidayDescriptionID, sizeof(this->m_holidayDescriptionID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &textureFileNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_priority, sizeof(this->m_priority), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_calendarFilterType, sizeof(this->m_calendarFilterType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flags, sizeof(this->m_flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_textureFileName = &stringBuffer[textureFileNameOfs];
    } else {
        this->m_textureFileName = "";
    }

    return true;
}
