// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_HOLIDAY_DESCRIPTIONS_REC_HPP
#define DB_REC_HOLIDAY_DESCRIPTIONS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class HolidayDescriptionsRec {
    public:
        static constexpr uint32_t columnCount = 18;
        static constexpr uint32_t rowSize = 72;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_description;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif