// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_CLASS_REC_HPP
#define DB_REC_ITEM_CLASS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ItemClassRec {
    public:
        static constexpr uint32_t columnCount = 20;
        static constexpr uint32_t rowSize = 80;
        static constexpr bool indexIsID = true;

        int32_t m_classID;
        int32_t m_subclassMapID;
        int32_t m_flags;
        const char* m_className;
        int32_t m_generatedID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif