// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_EXTENDED_COST_REC_HPP
#define DB_REC_ITEM_EXTENDED_COST_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ItemExtendedCostRec {
    public:
        static constexpr uint32_t columnCount = 16;
        static constexpr uint32_t rowSize = 64;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_honorPoints;
        int32_t m_arenaPoints;
        int32_t m_arenaBracket;
        int32_t m_itemID[5];
        int32_t m_itemCount[5];
        int32_t m_requiredArenaRating;
        int32_t m_itemPurchaseGroup;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif