// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ItemSetRec.hpp"
#include "util/SFile.hpp"

const char* ItemSetRec::GetFilename() {
    return "DBFilesClient\\ItemSet.dbc";
}

uint32_t ItemSetRec::GetNumColumns() {
    return 53;
}

uint32_t ItemSetRec::GetRowSize() {
    return 212;
}

bool ItemSetRec::NeedIDAssigned() {
    return false;
}

int32_t ItemSetRec::GetID() {
    return this->m_ID;
}

void ItemSetRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool ItemSetRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t nameOfs[16];
    uint32_t nameMask;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[0], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[1], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[2], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[3], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[4], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[5], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[6], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[7], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[8], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[9], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[10], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[11], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[12], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[13], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[14], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[15], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemID[16], sizeof(m_itemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[0], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[1], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[2], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[3], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[4], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[5], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[6], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setSpellID[7], sizeof(m_setSpellID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[0], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[1], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[2], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[3], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[4], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[5], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[6], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_setThreshold[7], sizeof(m_setThreshold[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_requiredSkill, sizeof(this->m_requiredSkill), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_requiredSkillRank, sizeof(this->m_requiredSkillRank), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_name = &stringBuffer[nameOfs[CURRENT_LANGUAGE]];
    } else {
        this->m_name = "";
    }

    return true;
}
