// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_ITEMCONDEXTCOSTS_REC_HPP
#define DB_ITEMCONDEXTCOSTS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct ItemCondExtCostsRec {
	static constexpr uint32_t columnCount = 4;
	static constexpr uint32_t rowSize = 16;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_CondExtendedCost;
	int32_t m_ItemExtendedCostEntry;
	int32_t m_ArenaSeason;

	static const char* GetFilename() {
		return "DBFilesClient\\ItemCondExtCosts.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_CondExtendedCost, sizeof(this->m_CondExtendedCost), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ItemExtendedCostEntry, sizeof(this->m_ItemExtendedCostEntry), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ArenaSeason, sizeof(this->m_ArenaSeason), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif