// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ItemRec.hpp"
#include "util/SFile.hpp"

const char* ItemRec::GetFilename() {
    return "DBFilesClient\\Item.dbc";
}

uint32_t ItemRec::GetNumColumns() {
    return 8;
}

uint32_t ItemRec::GetRowSize() {
    return 32;
}

bool ItemRec::NeedIDAssigned() {
    return false;
}

int32_t ItemRec::GetID() {
    return this->m_ID;
}

void ItemRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool ItemRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_classID, sizeof(this->m_classID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_subclassID, sizeof(this->m_subclassID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_soundOverrideSubclassID, sizeof(this->m_soundOverrideSubclassID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_material, sizeof(this->m_material), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_displayInfoID, sizeof(this->m_displayInfoID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_inventoryType, sizeof(this->m_inventoryType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_sheatheType, sizeof(this->m_sheatheType), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
