// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_CLASS_REC_HPP
#define DB_REC_ITEM_CLASS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ItemClassRec {
    public:
        int32_t m_classID;
        int32_t m_subclassMapID;
        int32_t m_flags;
        const char* m_className;
        int32_t m_generatedID;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif