// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ItemDamageTwoHandRec.hpp"

const char* ItemDamageTwoHandRec::GetFilename() {
    return "DBFilesClient\\ItemDamageTwoHand.dbc";
}

int32_t ItemDamageTwoHandRec::GetID() {
    return this->m_ID;
}

bool ItemDamageTwoHandRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[0], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[1], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[2], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[3], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[4], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[5], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_quality[6], sizeof(m_quality[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_itemLevel, sizeof(this->m_itemLevel), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
