// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_DAMAGE_ONE_HAND_CASTER_REC_HPP
#define DB_REC_ITEM_DAMAGE_ONE_HAND_CASTER_REC_HPP

#include <cstdint>

class SFile;

class ItemDamageOneHandCasterRec {
    public:
        int32_t m_ID;
        float m_quality[7];
        int32_t m_itemLevel;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif