// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_GROUP_SOUNDS_REC_HPP
#define DB_REC_ITEM_GROUP_SOUNDS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ItemGroupSoundsRec {
    public:
        static constexpr uint32_t columnCount = 5;
        static constexpr uint32_t rowSize = 20;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_sound[4];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif