// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_RANDOM_SUFFIX_REC_HPP
#define DB_REC_ITEM_RANDOM_SUFFIX_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ItemRandomSuffixRec {
    public:
        static constexpr uint32_t columnCount = 29;
        static constexpr uint32_t rowSize = 116;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        const char* m_internalName;
        int32_t m_enchantment[5];
        int32_t m_allocationPct[5];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif