// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_ITEMARMORTOTAL_REC_HPP
#define DB_ITEMARMORTOTAL_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct ItemArmorTotalRec {
	static constexpr uint32_t columnCount = 6;
	static constexpr uint32_t rowSize = 24;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_ItemLevel;
	float m_Cloth;
	float m_Leather;
	float m_Mail;
	float m_Plate;

	static const char* GetFilename() {
		return "DBFilesClient\\ItemArmorTotal.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ItemLevel, sizeof(this->m_ItemLevel), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Cloth, sizeof(this->m_Cloth), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Leather, sizeof(this->m_Leather), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Mail, sizeof(this->m_Mail), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Plate, sizeof(this->m_Plate), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif