// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_ITEM_VISUAL_EFFECTS_REC_HPP
#define DB_REC_ITEM_VISUAL_EFFECTS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class ItemVisualEffectsRec {
    public:
        static constexpr uint32_t columnCount = 2;
        static constexpr uint32_t rowSize = 8;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_Model;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif