// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_ITEMVISUALEFFECTS_REC_HPP
#define DB_ITEMVISUALEFFECTS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct ItemVisualEffectsRec {
	static constexpr uint32_t columnCount = 2;
	static constexpr uint32_t rowSize = 8;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_Model;

	static const char* GetFilename() {
		return "DBFilesClient\\ItemVisualEffects.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t ModelOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &ModelOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Model = &stringBuffer[ModelOfs];
		} else {
			this->m_Model = "";
		}

		return true;
	}
};

#endif