// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ItemExtendedCostRec.hpp"

const char* ItemExtendedCostRec::GetFilename() {
    return "DBFilesClient\\ItemExtendedCost.dbc";
}

bool ItemExtendedCostRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_HonorPoints, sizeof(this->m_HonorPoints), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ArenaPoints, sizeof(this->m_ArenaPoints), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ArenaBracket, sizeof(this->m_ArenaBracket), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemID[0], sizeof(m_ItemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemID[1], sizeof(m_ItemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemID[2], sizeof(m_ItemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemID[3], sizeof(m_ItemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemID[4], sizeof(m_ItemID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemCount[0], sizeof(m_ItemCount[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemCount[1], sizeof(m_ItemCount[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemCount[2], sizeof(m_ItemCount[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemCount[3], sizeof(m_ItemCount[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemCount[4], sizeof(m_ItemCount[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RequiredArenaRating, sizeof(this->m_RequiredArenaRating), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ItemPurchaseGroup, sizeof(this->m_ItemPurchaseGroup), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
