// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LANGUAGE_WORDS_REC_HPP
#define DB_REC_LANGUAGE_WORDS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class LanguageWordsRec {
    public:
        static constexpr uint32_t columnCount = 3;
        static constexpr uint32_t rowSize = 12;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_languageID;
        const char* m_word;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif