// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LFGDUNGEON_EXPANSION_REC_HPP
#define DB_REC_LFGDUNGEON_EXPANSION_REC_HPP

#include <cstdint>

class SFile;

class LFGDungeonExpansionRec {
    public:
        int32_t m_ID;
        int32_t m_lfgID;
        int32_t m_expansionLevel;
        int32_t m_randomID;
        int32_t m_hardLevelMin;
        int32_t m_hardLevelMax;
        int32_t m_targetLevelMin;
        int32_t m_targetLevelMax;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif