// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LIGHT_FLOAT_BAND_REC_HPP
#define DB_REC_LIGHT_FLOAT_BAND_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class LightFloatBandRec {
    public:
    static constexpr uint32_t columnCount = 34;
    static constexpr uint32_t rowSize = 136;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    int32_t m_Num;
    int32_t m_Time[16];
    float m_Data[16];

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif