// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/LightSkyboxRec.hpp"

const char* LightSkyboxRec::GetFilename() {
    return "DBFilesClient\\LightSkybox.dbc";
}

bool LightSkyboxRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t NameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Name = &stringBuffer[NameOfs];
    } else {
        this->m_Name = "";
    }

    return true;
}
