// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LIGHT_PARAMS_REC_HPP
#define DB_REC_LIGHT_PARAMS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class LightParamsRec {
    public:
        int32_t m_ID;
        int32_t m_highlightSky;
        int32_t m_lightSkyboxID;
        float m_glow;
        float m_waterShallowAlpha;
        float m_waterDeepAlpha;
        float m_oceanShallowAlpha;
        float m_oceanDeepAlpha;
        int32_t m_flags;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif