// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/LightSkyboxRec.hpp"

const char* LightSkyboxRec::GetFilename() {
    return "DBFilesClient\\LightSkybox.dbc";
}

int32_t LightSkyboxRec::GetID() {
    return this->m_ID;
}

bool LightSkyboxRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t nameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flags, sizeof(this->m_flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_name = &stringBuffer[nameOfs];
    } else {
        this->m_name = "";
    }

    return true;
}
