// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/LiquidObjectRec.hpp"
#include "util/SFile.hpp"

const char* LiquidObjectRec::GetFilename() {
    return "DBFilesClient\\LiquidObject.dbc";
}

uint32_t LiquidObjectRec::GetNumColumns() {
    return 6;
}

uint32_t LiquidObjectRec::GetRowSize() {
    return 24;
}

bool LiquidObjectRec::NeedIDAssigned() {
    return false;
}

int32_t LiquidObjectRec::GetID() {
    return this->m_ID;
}

void LiquidObjectRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool LiquidObjectRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flowDirection, sizeof(this->m_flowDirection), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flowSpeed, sizeof(this->m_flowSpeed), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_liquidTypeID, sizeof(this->m_liquidTypeID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_fishable, sizeof(this->m_fishable), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_reflection, sizeof(this->m_reflection), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
