// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/LiquidMaterialRec.hpp"

const char* LiquidMaterialRec::GetFilename() {
    return "DBFilesClient\\LiquidMaterial.dbc";
}

bool LiquidMaterialRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_LVF, sizeof(this->m_LVF), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
