// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_LOADINGSCREENTAXISPLINES_REC_HPP
#define DB_LOADINGSCREENTAXISPLINES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct LoadingScreenTaxiSplinesRec {
	static constexpr uint32_t columnCount = 19;
	static constexpr uint32_t rowSize = 76;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_PathID;
	float m_Locx[8];
	float m_Locy[8];
	int32_t m_LegIndex;

	static const char* GetFilename() {
		return "DBFilesClient\\LoadingScreenTaxiSplines.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PathID, sizeof(this->m_PathID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[0], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[1], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[2], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[3], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[4], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[5], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[6], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locx[7], sizeof(m_Locx[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[0], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[1], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[2], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[3], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[4], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[5], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[6], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Locy[7], sizeof(m_Locy[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_LegIndex, sizeof(this->m_LegIndex), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif