// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LOADING_SCREEN_TAXI_SPLINES_REC_HPP
#define DB_REC_LOADING_SCREEN_TAXI_SPLINES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class LoadingScreenTaxiSplinesRec {
    public:
        int32_t m_ID;
        int32_t m_pathID;
        float m_locx[8];
        float m_locy[8];
        int32_t m_legIndex;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif