// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_LOADINGSCREENS_REC_HPP
#define DB_LOADINGSCREENS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct LoadingScreensRec {
	static constexpr uint32_t columnCount = 4;
	static constexpr uint32_t rowSize = 16;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_Name;
	const char* m_FileName;
	int32_t m_HasWideScreen;

	static const char* GetFilename() {
		return "DBFilesClient\\LoadingScreens.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t NameOfs;
		uint32_t FileNameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &FileNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_HasWideScreen, sizeof(this->m_HasWideScreen), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Name = &stringBuffer[NameOfs];
			this->m_FileName = &stringBuffer[FileNameOfs];
		} else {
			this->m_Name = "";
			this->m_FileName = "";
		}

		return true;
	}
};

#endif