// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/LoadingScreenTaxiSplinesRec.hpp"

const char* LoadingScreenTaxiSplinesRec::GetFilename() {
    return "DBFilesClient\\LoadingScreenTaxiSplines.dbc";
}

int32_t LoadingScreenTaxiSplinesRec::GetNumColumns() {
    return 19;
}

int32_t LoadingScreenTaxiSplinesRec::GetRowSize() {
    return 76;
}

bool LoadingScreenTaxiSplinesRec::NeedIDAssigned() {
    return false;
}

int32_t LoadingScreenTaxiSplinesRec::GetID() {
    return this->m_ID;
}

void LoadingScreenTaxiSplinesRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool LoadingScreenTaxiSplinesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_pathID, sizeof(this->m_pathID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[0], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[1], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[2], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[3], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[4], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[5], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[6], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locx[7], sizeof(m_locx[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[0], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[1], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[2], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[3], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[4], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[5], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[6], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_locy[7], sizeof(m_locy[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_legIndex, sizeof(this->m_legIndex), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
