// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LOADING_SCREEN_TAXI_SPLINES_REC_HPP
#define DB_REC_LOADING_SCREEN_TAXI_SPLINES_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class LoadingScreenTaxiSplinesRec {
    public:
        static constexpr uint32_t columnCount = 19;
        static constexpr uint32_t rowSize = 76;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_PathID;
        float m_Locx[8];
        float m_Locy[8];
        int32_t m_LegIndex;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif