// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_LOCK_REC_HPP
#define DB_REC_LOCK_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class LockRec {
    public:
        static constexpr uint32_t columnCount = 33;
        static constexpr uint32_t rowSize = 132;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_type[8];
        int32_t m_index[8];
        int32_t m_skill[8];
        int32_t m_action[8];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif