// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_MAIL_TEMPLATE_REC_HPP
#define DB_REC_MAIL_TEMPLATE_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class MailTemplateRec {
    public:
        static constexpr uint32_t columnCount = 35;
        static constexpr uint32_t rowSize = 140;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_Subject_lang;
        const char* m_Body_lang;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif