// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_MAP_REC_HPP
#define DB_REC_MAP_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class MapRec {
    public:
        static constexpr uint32_t columnCount = 66;
        static constexpr uint32_t rowSize = 264;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_directory;
        int32_t m_instanceType;
        int32_t m_flags; // unconfirmed
        int32_t m_pvp;
        const char* m_mapName;
        int32_t m_areaTableID;
        const char* m_mapDescription0;
        const char* m_mapDescription1;
        int32_t m_loadingScreenID;
        float m_minimapIconScale;
        int32_t m_corpseMapID;
        float m_corpse[2];
        int32_t m_timeOfDayOverride;
        int32_t m_expansionID;
        int32_t m_raidOffset;
        int32_t m_maxPlayers;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif