// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/MountTypeRec.hpp"
#include "util/SFile.hpp"

const char* MountTypeRec::GetFilename() {
    return "DBFilesClient\\MountType.dbc";
}

uint32_t MountTypeRec::GetNumColumns() {
    return 9;
}

uint32_t MountTypeRec::GetRowSize() {
    return 36;
}

bool MountTypeRec::NeedIDAssigned() {
    return false;
}

int32_t MountTypeRec::GetID() {
    return this->m_ID;
}

void MountTypeRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool MountTypeRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[0], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[1], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[2], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[3], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[4], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[5], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[6], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_capability[7], sizeof(m_capability[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
