// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_MOVIEVARIATION_REC_HPP
#define DB_MOVIEVARIATION_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct MovieVariationRec {
	static constexpr uint32_t columnCount = 3;
	static constexpr uint32_t rowSize = 12;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_MovieID;
	int32_t m_FileDataID;

	static const char* GetFilename() {
		return "DBFilesClient\\MovieVariation.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_MovieID, sizeof(this->m_MovieID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_FileDataID, sizeof(this->m_FileDataID), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif