// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_NAME_GEN_REC_HPP
#define DB_REC_NAME_GEN_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class NameGenRec {
    public:
        static constexpr uint32_t columnCount = 4;
        static constexpr uint32_t rowSize = 16;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        int32_t m_raceID;
        int32_t m_sex;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif