// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_NAME_GEN_REC_HPP
#define DB_REC_NAME_GEN_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class NameGenRec {
    public:
    static constexpr uint32_t columnCount = 4;
    static constexpr uint32_t rowSize = 16;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    const char* m_Name;
    int32_t m_RaceID;
    int32_t m_Sex;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif