// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/NameGenRec.hpp"

const char* NameGenRec::GetFilename() {
    return "DBFilesClient\\NameGen.dbc";
}

int32_t NameGenRec::GetNumColumns() {
    return 4;
}

int32_t NameGenRec::GetRowSize() {
    return 16;
}

bool NameGenRec::NeedIDAssigned() {
    return false;
}

int32_t NameGenRec::GetID() {
    return this->m_ID;
}

void NameGenRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool NameGenRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t nameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_raceID, sizeof(this->m_raceID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_sex, sizeof(this->m_sex), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_name = &stringBuffer[nameOfs];
    } else {
        this->m_name = "";
    }

    return true;
}
