// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_NPCSOUNDS_REC_HPP
#define DB_NPCSOUNDS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct NPCSoundsRec {
	static constexpr uint32_t columnCount = 5;
	static constexpr uint32_t rowSize = 20;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_SoundID[4];

	static const char* GetFilename() {
		return "DBFilesClient\\NPCSounds.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundID[0], sizeof(m_SoundID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundID[1], sizeof(m_SoundID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundID[2], sizeof(m_SoundID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundID[3], sizeof(m_SoundID[0]), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif