// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_OBJECTEFFECTPACKAGE_REC_HPP
#define DB_OBJECTEFFECTPACKAGE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct ObjectEffectPackageRec {
	static constexpr uint32_t columnCount = 2;
	static constexpr uint32_t rowSize = 8;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_Name;

	static const char* GetFilename() {
		return "DBFilesClient\\ObjectEffectPackage.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t NameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Name = &stringBuffer[NameOfs];
		} else {
			this->m_Name = "";
		}

		return true;
	}
};

#endif