// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_OBJECT_EFFECT_REC_HPP
#define DB_REC_OBJECT_EFFECT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ObjectEffectRec {
    public:
        int32_t m_ID;
        const char* m_name;
        int32_t m_objectEffectGroupID;
        int32_t m_triggerType;
        int32_t m_eventType;
        int32_t m_effectRecType;
        int32_t m_effectRecID;
        int32_t m_attachment;
        float m_offset[3];
        int32_t m_objectEffectModifierID;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif