// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ObjectEffectModifierRec.hpp"

const char* ObjectEffectModifierRec::GetFilename() {
    return "DBFilesClient\\ObjectEffectModifier.dbc";
}

bool ObjectEffectModifierRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_InputType, sizeof(this->m_InputType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_MapType, sizeof(this->m_MapType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_OutputType, sizeof(this->m_OutputType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Param[0], sizeof(m_Param[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Param[1], sizeof(m_Param[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Param[2], sizeof(m_Param[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Param[3], sizeof(m_Param[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
