// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_OBJECTEFFECTPACKAGEELEM_REC_HPP
#define DB_OBJECTEFFECTPACKAGEELEM_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct ObjectEffectPackageElemRec {
	static constexpr uint32_t columnCount = 4;
	static constexpr uint32_t rowSize = 16;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_ObjectEffectPackageID;
	int32_t m_ObjectEffectGroupID;
	int32_t m_StateType;

	static const char* GetFilename() {
		return "DBFilesClient\\ObjectEffectPackageElem.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ObjectEffectPackageID, sizeof(this->m_ObjectEffectPackageID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ObjectEffectGroupID, sizeof(this->m_ObjectEffectGroupID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_StateType, sizeof(this->m_StateType), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif