// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_OVERRIDESPELLDATA_REC_HPP
#define DB_OVERRIDESPELLDATA_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct OverrideSpellDataRec {
	static constexpr uint32_t columnCount = 12;
	static constexpr uint32_t rowSize = 48;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_Spells[10];
	int32_t m_Flags;

	static const char* GetFilename() {
		return "DBFilesClient\\OverrideSpellData.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[0], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[1], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[2], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[3], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[4], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[5], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[6], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[7], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[8], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Spells[9], sizeof(m_Spells[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif