// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/PaperDollItemFrameRec.hpp"

const char* PaperDollItemFrameRec::GetFilename() {
    return "DBFilesClient\\PaperDollItemFrame.dbc";
}

bool PaperDollItemFrameRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t ItemButtonNameOfs;
    uint32_t SlotIconOfs;

    if (
        !SFile::Read(f, &ItemButtonNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &SlotIconOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SlotNumber, sizeof(this->m_SlotNumber), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_ItemButtonName = &stringBuffer[ItemButtonNameOfs];
        this->m_SlotIcon = &stringBuffer[SlotIconOfs];
    } else {
        this->m_ItemButtonName = "";
        this->m_SlotIcon = "";
    }

    return true;
}
