// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_PARTICLE_COLOR_REC_HPP
#define DB_REC_PARTICLE_COLOR_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class ParticleColorRec {
    public:
        static constexpr uint32_t columnCount = 10;
        static constexpr uint32_t rowSize = 40;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_start[3];
        int32_t m_mid[3];
        int32_t m_end[3];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif