// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/PetitionTypeRec.hpp"

const char* PetitionTypeRec::GetFilename() {
    return "DBFilesClient\\PetitionType.dbc";
}

int32_t PetitionTypeRec::GetID() {
    return this->m_ID;
}

bool PetitionTypeRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t nameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_type, sizeof(this->m_type), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_name = &stringBuffer[nameOfs];
    } else {
        this->m_name = "";
    }

    return true;
}
