// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_PETITION_TYPE_REC_HPP
#define DB_REC_PETITION_TYPE_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class PetitionTypeRec {
    public:
        static constexpr uint32_t columnCount = 3;
        static constexpr uint32_t rowSize = 12;
        static constexpr bool indexIsID = false;

        int32_t m_ID; // unconfirmed
        const char* m_Name; // unconfirmed
        int32_t m_Type; // unconfirmed

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif