// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_PET_PERSONALITY_REC_HPP
#define DB_REC_PET_PERSONALITY_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class PetPersonalityRec {
    public:
        static constexpr uint32_t columnCount = 24;
        static constexpr uint32_t rowSize = 96;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        int32_t m_happinessThreshold[3];
        float m_happinessDamage[3];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif