// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_PHASESHIFTZONESOUNDS_REC_HPP
#define DB_PHASESHIFTZONESOUNDS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct PhaseShiftZoneSoundsRec {
	static constexpr uint32_t columnCount = 14;
	static constexpr uint32_t rowSize = 56;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_AreaID;
	int32_t m_WMOAreaID;
	int32_t m_PhaseID;
	int32_t m_PhaseGroupID;
	int32_t m_PhaseUseFlags;
	int32_t m_ZoneIntroMusicID;
	int32_t m_ZoneMusicID;
	int32_t m_SoundAmbienceID;
	int32_t m_SoundProviderPreferencesID;
	int32_t m_UWZoneIntroMusicID;
	int32_t m_UWZoneMusicID;
	int32_t m_UWSoundAmbienceID;
	int32_t m_UWSoundProviderPreferencesID;

	static const char* GetFilename() {
		return "DBFilesClient\\PhaseShiftZoneSounds.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AreaID, sizeof(this->m_AreaID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_WMOAreaID, sizeof(this->m_WMOAreaID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PhaseID, sizeof(this->m_PhaseID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PhaseGroupID, sizeof(this->m_PhaseGroupID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PhaseUseFlags, sizeof(this->m_PhaseUseFlags), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ZoneIntroMusicID, sizeof(this->m_ZoneIntroMusicID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ZoneMusicID, sizeof(this->m_ZoneMusicID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundAmbienceID, sizeof(this->m_SoundAmbienceID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundProviderPreferencesID, sizeof(this->m_SoundProviderPreferencesID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_UWZoneIntroMusicID, sizeof(this->m_UWZoneIntroMusicID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_UWZoneMusicID, sizeof(this->m_UWZoneMusicID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_UWSoundAmbienceID, sizeof(this->m_UWSoundAmbienceID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_UWSoundProviderPreferencesID, sizeof(this->m_UWSoundProviderPreferencesID), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif