// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_PHASEXPHASEGROUP_REC_HPP
#define DB_PHASEXPHASEGROUP_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct PhaseXPhaseGroupRec {
	static constexpr uint32_t columnCount = 3;
	static constexpr uint32_t rowSize = 12;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_PhaseID;
	int32_t m_PhaseGroupID;

	static const char* GetFilename() {
		return "DBFilesClient\\PhaseXPhaseGroup.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PhaseID, sizeof(this->m_PhaseID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PhaseGroupID, sizeof(this->m_PhaseGroupID), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif