// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_PVPDIFFICULTY_REC_HPP
#define DB_REC_PVPDIFFICULTY_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class PVPDifficultyRec {
    public:
        static constexpr uint32_t columnCount = 6;
        static constexpr uint32_t rowSize = 24;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_MapID;
        int32_t m_RangeIndex;
        int32_t m_MinLevel;
        int32_t m_MaxLevel;
        int32_t m_Difficulty;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif