// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/QuestFactionRewardRec.hpp"

const char* QuestFactionRewardRec::GetFilename() {
    return "DBFilesClient\\QuestFactionReward.dbc";
}

int32_t QuestFactionRewardRec::GetNumColumns() {
    return 11;
}

int32_t QuestFactionRewardRec::GetRowSize() {
    return 44;
}

bool QuestFactionRewardRec::NeedIDAssigned() {
    return false;
}

int32_t QuestFactionRewardRec::GetID() {
    return this->m_ID;
}

void QuestFactionRewardRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool QuestFactionRewardRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[0], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[1], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[2], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[3], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[4], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[5], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[6], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[7], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[8], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_difficulty[9], sizeof(m_difficulty[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
