// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_RAND_PROP_POINTS_REC_HPP
#define DB_REC_RAND_PROP_POINTS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class RandPropPointsRec {
    public:
        static constexpr uint32_t columnCount = 16;
        static constexpr uint32_t rowSize = 64;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_epic[5];
        int32_t m_superior[5];
        int32_t m_good[5];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif