// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_RESEARCH_BRANCH_REC_HPP
#define DB_REC_RESEARCH_BRANCH_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class ResearchBranchRec {
    public:
        static constexpr uint32_t columnCount = 22;
        static constexpr uint32_t rowSize = 88;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_Name_lang;
        int32_t m_ResearchFieldID;
        int32_t m_CurrencyID;
        const char* m_Texture;
        int32_t m_ItemID;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif