// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ScalingStatDistributionRec.hpp"

const char* ScalingStatDistributionRec::GetFilename() {
    return "DBFilesClient\\ScalingStatDistribution.dbc";
}

int32_t ScalingStatDistributionRec::GetID() {
    return this->m_ID;
}

bool ScalingStatDistributionRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[0], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[1], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[2], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[3], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[4], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[5], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[6], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[7], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[8], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_statID[9], sizeof(m_statID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[0], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[1], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[2], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[3], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[4], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[5], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[6], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[7], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[8], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bonus[9], sizeof(m_bonus[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_maxlevel, sizeof(this->m_maxlevel), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
