// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SCALING_STAT_DISTRIBUTION_REC_HPP
#define DB_REC_SCALING_STAT_DISTRIBUTION_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class ScalingStatDistributionRec {
    public:
        static constexpr uint32_t columnCount = 22;
        static constexpr uint32_t rowSize = 88;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_StatID[10];
        int32_t m_Bonus[10];
        int32_t m_Maxlevel;

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif