// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SHEATHE_SOUND_LOOKUPS_REC_HPP
#define DB_REC_SHEATHE_SOUND_LOOKUPS_REC_HPP

#include <cstdint>

class SFile;

class SheatheSoundLookupsRec {
    public:
        int32_t m_ID;
        int32_t m_classID;
        int32_t m_subclassID;
        int32_t m_material;
        int32_t m_checkMaterial;
        int32_t m_sheatheSound;
        int32_t m_unsheatheSound;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif