// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SHEATHE_SOUND_LOOKUPS_REC_HPP
#define DB_REC_SHEATHE_SOUND_LOOKUPS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class SheatheSoundLookupsRec {
    public:
    static constexpr uint32_t columnCount = 7;
    static constexpr uint32_t rowSize = 28;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    int32_t m_ClassID;
    int32_t m_SubclassID;
    int32_t m_Material;
    int32_t m_CheckMaterial;
    int32_t m_SheatheSound;
    int32_t m_UnsheatheSound;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif