// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SKILL_LINE_REC_HPP
#define DB_REC_SKILL_LINE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SkillLineRec {
    public:
        static constexpr uint32_t columnCount = 56;
        static constexpr uint32_t rowSize = 224;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_categoryID;
        int32_t m_skillCostsID;
        const char* m_displayName;
        const char* m_description;
        int32_t m_spellIconID;
        const char* m_alternateVerb;
        int32_t m_canLink;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif