// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SKILL_TIERS_REC_HPP
#define DB_REC_SKILL_TIERS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SkillTiersRec {
    public:
        static constexpr uint32_t columnCount = 33;
        static constexpr uint32_t rowSize = 132;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_cost[16];
        int32_t m_value[16];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif