// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SKILL_RACE_CLASS_INFO_REC_HPP
#define DB_REC_SKILL_RACE_CLASS_INFO_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SkillRaceClassInfoRec {
    public:
        static constexpr uint32_t columnCount = 8;
        static constexpr uint32_t rowSize = 32;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_skillID;
        int32_t m_raceMask;
        int32_t m_classMask;
        int32_t m_flags;
        int32_t m_minLevel;
        int32_t m_skillTierID;
        int32_t m_skillCostIndex;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif