// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_SKILLRACECLASSINFO_REC_HPP
#define DB_SKILLRACECLASSINFO_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct SkillRaceClassInfoRec {
	static constexpr uint32_t columnCount = 8;
	static constexpr uint32_t rowSize = 32;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_SkillID;
	int32_t m_RaceMask;
	int32_t m_ClassMask;
	int32_t m_Flags;
	int32_t m_MinLevel;
	int32_t m_SkillTierID;
	int32_t m_SkillCostIndex;

	static const char* GetFilename() {
		return "DBFilesClient\\SkillRaceClassInfo.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SkillID, sizeof(this->m_SkillID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RaceMask, sizeof(this->m_RaceMask), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ClassMask, sizeof(this->m_ClassMask), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_MinLevel, sizeof(this->m_MinLevel), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SkillTierID, sizeof(this->m_SkillTierID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SkillCostIndex, sizeof(this->m_SkillCostIndex), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif