// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SKILL_LINE_REC_HPP
#define DB_REC_SKILL_LINE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SkillLineRec {
    public:
        int32_t m_ID;
        int32_t m_categoryID;
        int32_t m_skillCostsID;
        const char* m_displayName;
        const char* m_description;
        int32_t m_spellIconID;
        const char* m_alternateVerb;
        int32_t m_canLink;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif