// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SoundFilterElemRec.hpp"

const char* SoundFilterElemRec::GetFilename() {
    return "DBFilesClient\\SoundFilterElem.dbc";
}

bool SoundFilterElemRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SoundFilterID, sizeof(this->m_SoundFilterID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_OrderIndex, sizeof(this->m_OrderIndex), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_FilterType, sizeof(this->m_FilterType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[0], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[1], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[2], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[3], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[4], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[5], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[6], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[7], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Params[8], sizeof(m_Params[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
