// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SoundProviderPreferencesRec.hpp"

const char* SoundProviderPreferencesRec::GetFilename() {
    return "DBFilesClient\\SoundProviderPreferences.dbc";
}

bool SoundProviderPreferencesRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t DescriptionOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &DescriptionOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAXEnvironmentSelection, sizeof(this->m_EAXEnvironmentSelection), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAXDecayTime, sizeof(this->m_EAXDecayTime), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2EnvironmentSize, sizeof(this->m_EAX2EnvironmentSize), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2EnvironmentDiffusion, sizeof(this->m_EAX2EnvironmentDiffusion), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2Room, sizeof(this->m_EAX2Room), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2RoomHF, sizeof(this->m_EAX2RoomHF), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2DecayHFRatio, sizeof(this->m_EAX2DecayHFRatio), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2Reflections, sizeof(this->m_EAX2Reflections), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2ReflectionsDelay, sizeof(this->m_EAX2ReflectionsDelay), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2Reverb, sizeof(this->m_EAX2Reverb), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2ReverbDelay, sizeof(this->m_EAX2ReverbDelay), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2RoomRolloff, sizeof(this->m_EAX2RoomRolloff), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX2AirAbsorption, sizeof(this->m_EAX2AirAbsorption), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3RoomLF, sizeof(this->m_EAX3RoomLF), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3DecayLFRatio, sizeof(this->m_EAX3DecayLFRatio), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3EchoTime, sizeof(this->m_EAX3EchoTime), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3EchoDepth, sizeof(this->m_EAX3EchoDepth), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3ModulationTime, sizeof(this->m_EAX3ModulationTime), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3ModulationDepth, sizeof(this->m_EAX3ModulationDepth), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3HFReference, sizeof(this->m_EAX3HFReference), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EAX3LFReference, sizeof(this->m_EAX3LFReference), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Description = &stringBuffer[DescriptionOfs];
    } else {
        this->m_Description = "";
    }

    return true;
}
