// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SOUND_SAMPLE_PREFERENCES_REC_HPP
#define DB_REC_SOUND_SAMPLE_PREFERENCES_REC_HPP

#include <cstdint>

class SFile;

class SoundSamplePreferencesRec {
    public:
        int32_t m_ID;
        int32_t m_field_0_6_0_3592_001; // unconfirmed
        int32_t m_field_0_6_0_3592_002; // unconfirmed
        int32_t m_eax2SampleRoom;
        int32_t m_field_0_6_0_3592_004; // unconfirmed
        int32_t m_field_0_6_0_3592_005; // unconfirmed
        float m_field_0_6_0_3592_006; // unconfirmed
        int32_t m_field_0_6_0_3592_007; // unconfirmed
        float m_eax2SampleOcclusionLfratio;
        float m_eax2SampleOcclusionRoomRatio;
        int32_t m_field_0_6_0_3592_010; // unconfirmed
        float m_eax1EffectLevel;
        int32_t m_field_0_6_0_3592_012; // unconfirmed
        float m_field_0_6_0_3592_013; // unconfirmed
        float m_eax3SampleExclusion;
        float m_field_0_6_0_3592_015; // unconfirmed
        int32_t m_field_0_6_0_3592_016; // unconfirmed

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif