// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SoundProviderPreferencesRec.hpp"

const char* SoundProviderPreferencesRec::GetFilename() {
    return "DBFilesClient\\SoundProviderPreferences.dbc";
}

int32_t SoundProviderPreferencesRec::GetID() {
    return this->m_ID;
}

bool SoundProviderPreferencesRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t descriptionOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &descriptionOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flags, sizeof(this->m_flags), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eaxenvironmentSelection, sizeof(this->m_eaxenvironmentSelection), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eaxdecayTime, sizeof(this->m_eaxdecayTime), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2EnvironmentSize, sizeof(this->m_eax2EnvironmentSize), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2EnvironmentDiffusion, sizeof(this->m_eax2EnvironmentDiffusion), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2Room, sizeof(this->m_eax2Room), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2RoomHf, sizeof(this->m_eax2RoomHf), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2DecayHfratio, sizeof(this->m_eax2DecayHfratio), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2Reflections, sizeof(this->m_eax2Reflections), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2ReflectionsDelay, sizeof(this->m_eax2ReflectionsDelay), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2Reverb, sizeof(this->m_eax2Reverb), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2ReverbDelay, sizeof(this->m_eax2ReverbDelay), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2RoomRolloff, sizeof(this->m_eax2RoomRolloff), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax2AirAbsorption, sizeof(this->m_eax2AirAbsorption), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3RoomLf, sizeof(this->m_eax3RoomLf), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3DecayLfratio, sizeof(this->m_eax3DecayLfratio), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3EchoTime, sizeof(this->m_eax3EchoTime), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3EchoDepth, sizeof(this->m_eax3EchoDepth), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3ModulationTime, sizeof(this->m_eax3ModulationTime), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3ModulationDepth, sizeof(this->m_eax3ModulationDepth), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3Hfreference, sizeof(this->m_eax3Hfreference), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_eax3Lfreference, sizeof(this->m_eax3Lfreference), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_description = &stringBuffer[descriptionOfs];
    } else {
        this->m_description = "";
    }

    return true;
}
