// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_SOUNDENTRIESADVANCED_REC_HPP
#define DB_SOUNDENTRIESADVANCED_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct SoundEntriesAdvancedRec {
	static constexpr uint32_t columnCount = 24;
	static constexpr uint32_t rowSize = 96;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_SoundEntryID;
	float m_InnerRadius2D;
	int32_t m_TimeA;
	int32_t m_TimeB;
	int32_t m_TimeC;
	int32_t m_TimeD;
	int32_t m_RandomOffsetRange;
	int32_t m_Usage;
	int32_t m_TimeIntervalMin;
	int32_t m_TimeIntervalMax;
	int32_t m_VolumeSliderCategory;
	float m_DuckToSFX;
	float m_DuckToMusic;
	float m_DuckToAmbience;
	float m_InnerRadiusOfInfluence;
	float m_OuterRadiusOfInfluence;
	int32_t m_TimeToDuck;
	int32_t m_TimeToUnduck;
	float m_InsideAngle;
	float m_OutsideAngle;
	float m_OutsideVolume;
	float m_OuterRadius2D;
	const char* m_Name;

	static const char* GetFilename() {
		return "DBFilesClient\\SoundEntriesAdvanced.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t NameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundEntryID, sizeof(this->m_SoundEntryID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_InnerRadius2D, sizeof(this->m_InnerRadius2D), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeA, sizeof(this->m_TimeA), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeB, sizeof(this->m_TimeB), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeC, sizeof(this->m_TimeC), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeD, sizeof(this->m_TimeD), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RandomOffsetRange, sizeof(this->m_RandomOffsetRange), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Usage, sizeof(this->m_Usage), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeIntervalMin, sizeof(this->m_TimeIntervalMin), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeIntervalMax, sizeof(this->m_TimeIntervalMax), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VolumeSliderCategory, sizeof(this->m_VolumeSliderCategory), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DuckToSFX, sizeof(this->m_DuckToSFX), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DuckToMusic, sizeof(this->m_DuckToMusic), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_DuckToAmbience, sizeof(this->m_DuckToAmbience), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_InnerRadiusOfInfluence, sizeof(this->m_InnerRadiusOfInfluence), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_OuterRadiusOfInfluence, sizeof(this->m_OuterRadiusOfInfluence), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeToDuck, sizeof(this->m_TimeToDuck), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_TimeToUnduck, sizeof(this->m_TimeToUnduck), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_InsideAngle, sizeof(this->m_InsideAngle), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_OutsideAngle, sizeof(this->m_OutsideAngle), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_OutsideVolume, sizeof(this->m_OutsideVolume), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_OuterRadius2D, sizeof(this->m_OuterRadius2D), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Name = &stringBuffer[NameOfs];
		} else {
			this->m_Name = "";
		}

		return true;
	}
};

#endif