// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SoundAmbienceRec.hpp"

const char* SoundAmbienceRec::GetFilename() {
    return "DBFilesClient\\SoundAmbience.dbc";
}

bool SoundAmbienceRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_AmbienceID[0], sizeof(m_AmbienceID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_AmbienceID[1], sizeof(m_AmbienceID[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
