// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SOUND_AMBIENCE_REC_HPP
#define DB_REC_SOUND_AMBIENCE_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class SoundAmbienceRec {
    public:
    static constexpr uint32_t columnCount = 3;
    static constexpr uint32_t rowSize = 12;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    int32_t m_AmbienceID[2];

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif