// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SOUND_WATER_TYPE_REC_HPP
#define DB_REC_SOUND_WATER_TYPE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SoundWaterTypeRec {
    public:
        int32_t m_ID;
        int32_t m_soundType;
        int32_t m_soundSubtype;
        int32_t m_soundID;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif