// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_INTERRUPTS_REC_HPP
#define DB_REC_SPELL_INTERRUPTS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SpellInterruptsRec {
    public:
        static constexpr uint32_t columnCount = 6;
        static constexpr uint32_t rowSize = 24;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_auraInterruptFlags[2];
        int32_t m_channelInterruptFlags[2];
        int32_t m_interruptFlags;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif