// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_SPELLTOTEMS_REC_HPP
#define DB_SPELLTOTEMS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct SpellTotemsRec {
	static constexpr uint32_t columnCount = 5;
	static constexpr uint32_t rowSize = 20;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_RequiredTotemCategoryID[2];
	int32_t m_Totem[2];

	static const char* GetFilename() {
		return "DBFilesClient\\SpellTotems.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RequiredTotemCategoryID[0], sizeof(m_RequiredTotemCategoryID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RequiredTotemCategoryID[1], sizeof(m_RequiredTotemCategoryID[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Totem[0], sizeof(m_Totem[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Totem[1], sizeof(m_Totem[0]), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif