// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellVisualKitRec.hpp"

const char* SpellVisualKitRec::GetFilename() {
    return "DBFilesClient\\SpellVisualKit.dbc";
}

int32_t SpellVisualKitRec::GetID() {
    return this->m_ID;
}

bool SpellVisualKitRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_startAnimID, sizeof(this->m_startAnimID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_animID, sizeof(this->m_animID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_headEffect, sizeof(this->m_headEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_chestEffect, sizeof(this->m_chestEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_baseEffect, sizeof(this->m_baseEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_leftHandEffect, sizeof(this->m_leftHandEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rightHandEffect, sizeof(this->m_rightHandEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_breathEffect, sizeof(this->m_breathEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_leftWeaponEffect, sizeof(this->m_leftWeaponEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rightWeaponEffect, sizeof(this->m_rightWeaponEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_specialEffect[0], sizeof(m_specialEffect[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_specialEffect[1], sizeof(m_specialEffect[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_specialEffect[2], sizeof(m_specialEffect[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_worldEffect, sizeof(this->m_worldEffect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_soundID, sizeof(this->m_soundID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_shakeID, sizeof(this->m_shakeID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charProc[0], sizeof(m_charProc[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charProc[1], sizeof(m_charProc[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charProc[2], sizeof(m_charProc[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charProc[3], sizeof(m_charProc[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamZero[0], sizeof(m_charParamZero[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamZero[1], sizeof(m_charParamZero[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamZero[2], sizeof(m_charParamZero[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamZero[3], sizeof(m_charParamZero[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamOne[0], sizeof(m_charParamOne[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamOne[1], sizeof(m_charParamOne[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamOne[2], sizeof(m_charParamOne[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamOne[3], sizeof(m_charParamOne[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamTwo[0], sizeof(m_charParamTwo[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamTwo[1], sizeof(m_charParamTwo[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamTwo[2], sizeof(m_charParamTwo[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamTwo[3], sizeof(m_charParamTwo[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamThree[0], sizeof(m_charParamThree[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamThree[1], sizeof(m_charParamThree[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamThree[2], sizeof(m_charParamThree[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_charParamThree[3], sizeof(m_charParamThree[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flags, sizeof(this->m_flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
