// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellEffectRec.hpp"

const char* SpellEffectRec::GetFilename() {
    return "DBFilesClient\\SpellEffect.dbc";
}

bool SpellEffectRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Effect, sizeof(this->m_Effect), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectAmplitude, sizeof(this->m_EffectAmplitude), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectAura, sizeof(this->m_EffectAura), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectAuraPeriod, sizeof(this->m_EffectAuraPeriod), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectBasePoints, sizeof(this->m_EffectBasePoints), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectBonusCoefficient, sizeof(this->m_EffectBonusCoefficient), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectChainAmplitude, sizeof(this->m_EffectChainAmplitude), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectChainTargets, sizeof(this->m_EffectChainTargets), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectDieSides, sizeof(this->m_EffectDieSides), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectItemType, sizeof(this->m_EffectItemType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectMechanic, sizeof(this->m_EffectMechanic), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectMiscValue[0], sizeof(m_EffectMiscValue[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectMiscValue[1], sizeof(m_EffectMiscValue[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectPointsPerResource, sizeof(this->m_EffectPointsPerResource), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectRadiusIndex[0], sizeof(m_EffectRadiusIndex[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectRadiusIndex[1], sizeof(m_EffectRadiusIndex[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectRealPointsPerLevel, sizeof(this->m_EffectRealPointsPerLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectSpellClassMask[0], sizeof(m_EffectSpellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectSpellClassMask[1], sizeof(m_EffectSpellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectSpellClassMask[2], sizeof(m_EffectSpellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectTriggerSpell, sizeof(this->m_EffectTriggerSpell), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImplicitTarget[0], sizeof(m_ImplicitTarget[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImplicitTarget[1], sizeof(m_ImplicitTarget[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SpellID, sizeof(this->m_SpellID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_EffectIndex, sizeof(this->m_EffectIndex), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
