// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_VISUAL_KIT_REC_HPP
#define DB_REC_SPELL_VISUAL_KIT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SpellVisualKitRec {
    public:
        static constexpr uint32_t columnCount = 38;
        static constexpr uint32_t rowSize = 152;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_startAnimID;
        int32_t m_animID;
        int32_t m_headEffect;
        int32_t m_chestEffect;
        int32_t m_baseEffect;
        int32_t m_leftHandEffect;
        int32_t m_rightHandEffect;
        int32_t m_breathEffect;
        int32_t m_leftWeaponEffect;
        int32_t m_rightWeaponEffect;
        int32_t m_specialEffect[3];
        int32_t m_worldEffect;
        int32_t m_soundID;
        int32_t m_shakeID;
        int32_t m_charProc[4];
        float m_charParamZero[4];
        float m_charParamOne[4];
        float m_charParamTwo[4];
        float m_charParamThree[4];
        int32_t m_flags;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif