// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellEffectCameraShakesRec.hpp"

const char* SpellEffectCameraShakesRec::GetFilename() {
    return "DBFilesClient\\SpellEffectCameraShakes.dbc";
}

bool SpellEffectCameraShakesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CameraShake[0], sizeof(m_CameraShake[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CameraShake[1], sizeof(m_CameraShake[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CameraShake[2], sizeof(m_CameraShake[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
