// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellAuraRestrictionsRec.hpp"

const char* SpellAuraRestrictionsRec::GetFilename() {
    return "DBFilesClient\\SpellAuraRestrictions.dbc";
}

int32_t SpellAuraRestrictionsRec::GetNumColumns() {
    return 9;
}

int32_t SpellAuraRestrictionsRec::GetRowSize() {
    return 36;
}

bool SpellAuraRestrictionsRec::NeedIDAssigned() {
    return false;
}

int32_t SpellAuraRestrictionsRec::GetID() {
    return this->m_ID;
}

void SpellAuraRestrictionsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool SpellAuraRestrictionsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_casterAuraState, sizeof(this->m_casterAuraState), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_targetAuraState, sizeof(this->m_targetAuraState), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_excludeCasterAuraState, sizeof(this->m_excludeCasterAuraState), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_excludeTargetAuraState, sizeof(this->m_excludeTargetAuraState), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_casterAuraSpell, sizeof(this->m_casterAuraSpell), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_targetAuraSpell, sizeof(this->m_targetAuraSpell), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_excludeCasterAuraSpell, sizeof(this->m_excludeCasterAuraSpell), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_excludeTargetAuraSpell, sizeof(this->m_excludeTargetAuraSpell), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
