// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellLevelsRec.hpp"

const char* SpellLevelsRec::GetFilename() {
    return "DBFilesClient\\SpellLevels.dbc";
}

int32_t SpellLevelsRec::GetID() {
    return this->m_ID;
}

bool SpellLevelsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_baseLevel, sizeof(this->m_baseLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_maxLevel, sizeof(this->m_maxLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spellLevel, sizeof(this->m_spellLevel), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
