// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellRadiusRec.hpp"
#include "util/SFile.hpp"

const char* SpellRadiusRec::GetFilename() {
    return "DBFilesClient\\SpellRadius.dbc";
}

uint32_t SpellRadiusRec::GetNumColumns() {
    return 4;
}

uint32_t SpellRadiusRec::GetRowSize() {
    return 16;
}

bool SpellRadiusRec::NeedIDAssigned() {
    return false;
}

int32_t SpellRadiusRec::GetID() {
    return this->m_ID;
}

void SpellRadiusRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool SpellRadiusRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_radius, sizeof(this->m_radius), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_radiusPerLevel, sizeof(this->m_radiusPerLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_radiusMax, sizeof(this->m_radiusMax), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
