// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellClassOptionsRec.hpp"
#include "util/SFile.hpp"

const char* SpellClassOptionsRec::GetFilename() {
    return "DBFilesClient\\SpellClassOptions.dbc";
}

uint32_t SpellClassOptionsRec::GetNumColumns() {
    return 6;
}

uint32_t SpellClassOptionsRec::GetRowSize() {
    return 24;
}

bool SpellClassOptionsRec::NeedIDAssigned() {
    return false;
}

int32_t SpellClassOptionsRec::GetID() {
    return this->m_ID;
}

void SpellClassOptionsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool SpellClassOptionsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_modalNextSpell, sizeof(this->m_modalNextSpell), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spellClassMask[0], sizeof(m_spellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spellClassMask[1], sizeof(m_spellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spellClassMask[2], sizeof(m_spellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_spellClassSet, sizeof(this->m_spellClassSet), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
