// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_VISUAL_KIT_AREA_MODEL_REC_HPP
#define DB_REC_SPELL_VISUAL_KIT_AREA_MODEL_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class SpellVisualKitAreaModelRec {
    public:
    static constexpr uint32_t columnCount = 3;
    static constexpr uint32_t rowSize = 12;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    const char* m_Name;
    int32_t m_EnumID;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif