// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellClassOptionsRec.hpp"

const char* SpellClassOptionsRec::GetFilename() {
    return "DBFilesClient\\SpellClassOptions.dbc";
}

bool SpellClassOptionsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ModalNextSpell, sizeof(this->m_ModalNextSpell), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SpellClassMask[0], sizeof(m_SpellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SpellClassMask[1], sizeof(m_SpellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SpellClassMask[2], sizeof(m_SpellClassMask[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SpellClassSet, sizeof(this->m_SpellClassSet), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
