// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellVisualPrecastTransitionsRec.hpp"

const char* SpellVisualPrecastTransitionsRec::GetFilename() {
    return "DBFilesClient\\SpellVisualPrecastTransitions.dbc";
}

int32_t SpellVisualPrecastTransitionsRec::GetNumColumns() {
    return 3;
}

int32_t SpellVisualPrecastTransitionsRec::GetRowSize() {
    return 12;
}

bool SpellVisualPrecastTransitionsRec::NeedIDAssigned() {
    return false;
}

int32_t SpellVisualPrecastTransitionsRec::GetID() {
    return this->m_ID;
}

void SpellVisualPrecastTransitionsRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool SpellVisualPrecastTransitionsRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t precastLoadAnimNameOfs;
    uint32_t precastHoldAnimNameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &precastLoadAnimNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &precastHoldAnimNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_precastLoadAnimName = &stringBuffer[precastLoadAnimNameOfs];
        this->m_precastHoldAnimName = &stringBuffer[precastHoldAnimNameOfs];
    } else {
        this->m_precastLoadAnimName = "";
        this->m_precastHoldAnimName = "";
    }

    return true;
}
