// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellVisualKitAreaModelRec.hpp"

const char* SpellVisualKitAreaModelRec::GetFilename() {
    return "DBFilesClient\\SpellVisualKitAreaModel.dbc";
}

int32_t SpellVisualKitAreaModelRec::GetID() {
    return this->m_ID;
}

bool SpellVisualKitAreaModelRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t nameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &nameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enumID, sizeof(this->m_enumID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_name = &stringBuffer[nameOfs];
    } else {
        this->m_name = "";
    }

    return true;
}
