// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_SCALING_REC_HPP
#define DB_REC_SPELL_SCALING_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SpellScalingRec {
    public:
        static constexpr uint32_t columnCount = 16;
        static constexpr uint32_t rowSize = 64;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_castTimeMin;
        int32_t m_castTimeMax;
        int32_t m_castTimeMaxLevel;
        int32_t m_class;
        float m_coefficient[3];
        float m_variance[3];
        float m_comboPointsCoefficient[3];
        float m_nerfFactor;
        int32_t m_nerfMaxLevel;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif