// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_CAST_TIMES_REC_HPP
#define DB_REC_SPELL_CAST_TIMES_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class SpellCastTimesRec {
    public:
    static constexpr uint32_t columnCount = 4;
    static constexpr uint32_t rowSize = 16;
    static constexpr bool indexIsID = false;

    int32_t m_ID;
    int32_t m_Base;
    int32_t m_PerLevel;
    int32_t m_Minimum;

    static const char* GetFilename();
    bool Read(SFile* f, const char* stringBuffer);
};

#endif