// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellCastTimesRec.hpp"

const char* SpellCastTimesRec::GetFilename() {
    return "DBFilesClient\\SpellCastTimes.dbc";
}

bool SpellCastTimesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Base, sizeof(this->m_Base), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_PerLevel, sizeof(this->m_PerLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Minimum, sizeof(this->m_Minimum), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
