// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_SPELLVISUALPRECASTTRANSITIONS_REC_HPP
#define DB_SPELLVISUALPRECASTTRANSITIONS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct SpellVisualPrecastTransitionsRec {
	static constexpr uint32_t columnCount = 3;
	static constexpr uint32_t rowSize = 12;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_PrecastLoadAnimName;
	const char* m_PrecastHoldAnimName;

	static const char* GetFilename() {
		return "DBFilesClient\\SpellVisualPrecastTransitions.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t PrecastLoadAnimNameOfs;
		uint32_t PrecastHoldAnimNameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &PrecastLoadAnimNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &PrecastHoldAnimNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_PrecastLoadAnimName = &stringBuffer[PrecastLoadAnimNameOfs];
			this->m_PrecastHoldAnimName = &stringBuffer[PrecastHoldAnimNameOfs];
		} else {
			this->m_PrecastLoadAnimName = "";
			this->m_PrecastHoldAnimName = "";
		}

		return true;
	}
};

#endif