// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_MISSILE_MOTION_REC_HPP
#define DB_REC_SPELL_MISSILE_MOTION_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SpellMissileMotionRec {
    public:
        static constexpr uint32_t columnCount = 5;
        static constexpr uint32_t rowSize = 20;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        const char* m_scriptBody;
        int32_t m_flags;
        int32_t m_missileCount;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif