// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_RADIUS_REC_HPP
#define DB_REC_SPELL_RADIUS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SpellRadiusRec {
    public:
        static constexpr uint32_t columnCount = 4;
        static constexpr uint32_t rowSize = 16;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        float m_radius;
        float m_radiusPerLevel;
        float m_radiusMax;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif