// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellDurationRec.hpp"

const char* SpellDurationRec::GetFilename() {
    return "DBFilesClient\\SpellDuration.dbc";
}

bool SpellDurationRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Duration, sizeof(this->m_Duration), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_DurationPerLevel, sizeof(this->m_DurationPerLevel), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_MaxDuration, sizeof(this->m_MaxDuration), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
