// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/SpellAuraOptionsRec.hpp"

const char* SpellAuraOptionsRec::GetFilename() {
    return "DBFilesClient\\SpellAuraOptions.dbc";
}

bool SpellAuraOptionsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CumulativeAura, sizeof(this->m_CumulativeAura), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ProcChance, sizeof(this->m_ProcChance), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ProcCharges, sizeof(this->m_ProcCharges), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ProcTypeMask, sizeof(this->m_ProcTypeMask), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
