// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_AURA_RESTRICTIONS_REC_HPP
#define DB_REC_SPELL_AURA_RESTRICTIONS_REC_HPP

#include <cstdint>

class SFile;

class SpellAuraRestrictionsRec {
    public:
        int32_t m_ID;
        int32_t m_casterAuraState;
        int32_t m_targetAuraState;
        int32_t m_excludeCasterAuraState;
        int32_t m_excludeTargetAuraState;
        int32_t m_casterAuraSpell;
        int32_t m_targetAuraSpell;
        int32_t m_excludeCasterAuraSpell;
        int32_t m_excludeTargetAuraSpell;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif