// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_SPELLVISUALEFFECTNAME_REC_HPP
#define DB_SPELLVISUALEFFECTNAME_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct SpellVisualEffectNameRec {
	static constexpr uint32_t columnCount = 7;
	static constexpr uint32_t rowSize = 28;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_Name;
	const char* m_FileName;
	float m_AreaEffectSize;
	float m_Scale;
	float m_MinAllowedScale;
	float m_MaxAllowedScale;

	static const char* GetFilename() {
		return "DBFilesClient\\SpellVisualEffectName.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t NameOfs;
		uint32_t FileNameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &FileNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AreaEffectSize, sizeof(this->m_AreaEffectSize), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Scale, sizeof(this->m_Scale), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_MinAllowedScale, sizeof(this->m_MinAllowedScale), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_MaxAllowedScale, sizeof(this->m_MaxAllowedScale), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Name = &stringBuffer[NameOfs];
			this->m_FileName = &stringBuffer[FileNameOfs];
		} else {
			this->m_Name = "";
			this->m_FileName = "";
		}

		return true;
	}
};

#endif