// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_ITEM_ENCHANTMENT_CONDITION_REC_HPP
#define DB_REC_SPELL_ITEM_ENCHANTMENT_CONDITION_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class SpellItemEnchantmentConditionRec {
    public:
        static constexpr uint32_t columnCount = 31;
        static constexpr uint32_t rowSize = 64;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int8_t m_ltOperandType[5];
        int32_t m_ltOperand[5];
        int8_t m_operator[5];
        int8_t m_rtOperandType[5];
        int32_t m_rtOperand[5];
        int8_t m_logic[5];

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif