// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_SPELL_DIFFICULTY_REC_HPP
#define DB_REC_SPELL_DIFFICULTY_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class SpellDifficultyRec {
    public:
        static constexpr uint32_t columnCount = 5;
        static constexpr uint32_t rowSize = 20;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_DifficultySpellID[4];

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif