// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/StableSlotPricesRec.hpp"

const char* StableSlotPricesRec::GetFilename() {
    return "DBFilesClient\\StableSlotPrices.dbc";
}

bool StableSlotPricesRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Cost, sizeof(this->m_Cost), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
