// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_STABLESLOTPRICES_REC_HPP
#define DB_STABLESLOTPRICES_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct StableSlotPricesRec {
	static constexpr uint32_t columnCount = 2;
	static constexpr uint32_t rowSize = 8;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_Cost;

	static const char* GetFilename() {
		return "DBFilesClient\\StableSlotPrices.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Cost, sizeof(this->m_Cost), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif