// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_STARTUP_STRINGS_REC_HPP
#define DB_REC_STARTUP_STRINGS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class Startup_StringsRec {
    public:
        static constexpr uint32_t columnCount = 19;
        static constexpr uint32_t rowSize = 76;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        const char* m_name;
        const char* m_message;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif