// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/StringLookupsRec.hpp"

const char* StringLookupsRec::GetFilename() {
    return "DBFilesClient\\StringLookups.dbc";
}

bool StringLookupsRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t StringOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &StringOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_String = &stringBuffer[StringOfs];
    } else {
        this->m_String = "";
    }

    return true;
}
