// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_TALENT_TAB_REC_HPP
#define DB_REC_TALENT_TAB_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class TalentTabRec {
    public:
        int32_t m_ID;
        const char* m_name;
        int32_t m_spellIconID;
        int32_t m_raceMask;
        int32_t m_classMask;
        int32_t m_categoryEnumID; // unconfirmed
        int32_t m_orderIndex;
        const char* m_backgroundFile;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif