// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/TaxiPathRec.hpp"
#include "util/SFile.hpp"

const char* TaxiPathRec::GetFilename() {
    return "DBFilesClient\\TaxiPath.dbc";
}

uint32_t TaxiPathRec::GetNumColumns() {
    return 4;
}

uint32_t TaxiPathRec::GetRowSize() {
    return 16;
}

bool TaxiPathRec::NeedIDAssigned() {
    return false;
}

int32_t TaxiPathRec::GetID() {
    return this->m_ID;
}

void TaxiPathRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool TaxiPathRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_fromTaxiNode, sizeof(this->m_fromTaxiNode), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_toTaxiNode, sizeof(this->m_toTaxiNode), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_cost, sizeof(this->m_cost), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
