// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_TAXI_PATH_NODE_REC_HPP
#define DB_REC_TAXI_PATH_NODE_REC_HPP

#include <cstdint>

class SFile;

class TaxiPathNodeRec {
    public:
        int32_t m_ID;
        int32_t m_pathID;
        int32_t m_nodeIndex;
        int32_t m_continentID;
        float m_loc[3];
        int32_t m_flags;
        int32_t m_delay;
        int32_t m_arrivalEventID;
        int32_t m_departureEventID;

        static const char* GetFilename();
        static uint32_t GetNumColumns();
        static uint32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif