// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/TeamContributionPointsRec.hpp"

const char* TeamContributionPointsRec::GetFilename() {
    return "DBFilesClient\\TeamContributionPoints.dbc";
}

int32_t TeamContributionPointsRec::GetID() {
    return this->m_ID;
}

bool TeamContributionPointsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_data, sizeof(this->m_data), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
