// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/TerrainMaterialRec.hpp"

const char* TerrainMaterialRec::GetFilename() {
    return "DBFilesClient\\TerrainMaterial.dbc";
}

bool TerrainMaterialRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t NameOfs;
    uint32_t EnvMapPathOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Shader, sizeof(this->m_Shader), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &EnvMapPathOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Name = &stringBuffer[NameOfs];
        this->m_EnvMapPath = &stringBuffer[EnvMapPathOfs];
    } else {
        this->m_Name = "";
        this->m_EnvMapPath = "";
    }

    return true;
}
