// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_TERRAINTYPE_REC_HPP
#define DB_TERRAINTYPE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct TerrainTypeRec {
	static constexpr uint32_t columnCount = 6;
	static constexpr uint32_t rowSize = 24;
	static constexpr bool indexIsID = true;

	int32_t m_TerrainID;
	const char* m_TerrainDesc;
	int32_t m_FootstepSprayRun;
	int32_t m_FootstepSprayWalk;
	int32_t m_SoundID;
	int32_t m_Flags;

	static const char* GetFilename() {
		return "DBFilesClient\\TerrainType.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t TerrainDescOfs;

		if (
			!SFile::Read(f, &this->m_TerrainID, sizeof(this->m_TerrainID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &TerrainDescOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_FootstepSprayRun, sizeof(this->m_FootstepSprayRun), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_FootstepSprayWalk, sizeof(this->m_FootstepSprayWalk), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundID, sizeof(this->m_SoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Flags, sizeof(this->m_Flags), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_TerrainDesc = &stringBuffer[TerrainDescOfs];
		} else {
			this->m_TerrainDesc = "";
		}

		return true;
	}
};

#endif