// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/TerrainTypeRec.hpp"
#include "util/SFile.hpp"

const char* TerrainTypeRec::GetFilename() {
    return "DBFilesClient\\TerrainType.dbc";
}

uint32_t TerrainTypeRec::GetNumColumns() {
    return 6;
}

uint32_t TerrainTypeRec::GetRowSize() {
    return 24;
}

bool TerrainTypeRec::NeedIDAssigned() {
    return true;
}

int32_t TerrainTypeRec::GetID() {
    return this->m_generatedID;
}

void TerrainTypeRec::SetID(int32_t id) {
    this->m_generatedID = id;
}

bool TerrainTypeRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t terrainDescOfs;

    if (
        !SFile::Read(f, &this->m_terrainID, sizeof(this->m_terrainID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &terrainDescOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_footstepSprayRun, sizeof(this->m_footstepSprayRun), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_footstepSprayWalk, sizeof(this->m_footstepSprayWalk), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_soundID, sizeof(this->m_soundID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_flags, sizeof(this->m_flags), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_terrainDesc = &stringBuffer[terrainDescOfs];
    } else {
        this->m_terrainDesc = "";
    }

    return true;
}
