// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_TRANSPORT_ANIMATION_REC_HPP
#define DB_REC_TRANSPORT_ANIMATION_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class TransportAnimationRec {
    public:
        static constexpr uint32_t columnCount = 7;
        static constexpr uint32_t rowSize = 28;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_transportID;
        int32_t m_timeIndex;
        float m_pos[3];
        int32_t m_sequenceID;

        static const char* GetFilename();
        int32_t GetID();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif