// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/TransportRotationRec.hpp"
#include "util/SFile.hpp"

const char* TransportRotationRec::GetFilename() {
    return "DBFilesClient\\TransportRotation.dbc";
}

uint32_t TransportRotationRec::GetNumColumns() {
    return 7;
}

uint32_t TransportRotationRec::GetRowSize() {
    return 28;
}

bool TransportRotationRec::NeedIDAssigned() {
    return false;
}

int32_t TransportRotationRec::GetID() {
    return this->m_ID;
}

void TransportRotationRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool TransportRotationRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_gameObjectsID, sizeof(this->m_gameObjectsID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_timeIndex, sizeof(this->m_timeIndex), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rot[0], sizeof(m_rot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rot[1], sizeof(m_rot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rot[2], sizeof(m_rot[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rot[3], sizeof(m_rot[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
