// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_TRANSPORT_ROTATION_REC_HPP
#define DB_REC_TRANSPORT_ROTATION_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class TransportRotationRec {
    public:
        static constexpr uint32_t columnCount = 7;
        static constexpr uint32_t rowSize = 28;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_GameObjectsID;
        int32_t m_TimeIndex;
        float m_Rot[4];

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif