// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_UNITBLOODLEVELS_REC_HPP
#define DB_UNITBLOODLEVELS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct UnitBloodLevelsRec {
	static constexpr uint32_t columnCount = 4;
	static constexpr uint32_t rowSize = 16;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_Violencelevel[3];

	static const char* GetFilename() {
		return "DBFilesClient\\UnitBloodLevels.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Violencelevel[0], sizeof(m_Violencelevel[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Violencelevel[1], sizeof(m_Violencelevel[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Violencelevel[2], sizeof(m_Violencelevel[0]), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif