// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_UNIT_BLOOD_LEVELS_REC_HPP
#define DB_REC_UNIT_BLOOD_LEVELS_REC_HPP

#include <cstdint>
#include <storm/File.hpp>

class UnitBloodLevelsRec {
    public:
        static constexpr uint32_t columnCount = 4;
        static constexpr uint32_t rowSize = 16;
        static constexpr bool indexIsID = false;

        int32_t m_ID;
        int32_t m_Violencelevel[3];

        static const char* GetFilename();
        bool Read(SFile* f, const char* stringBuffer);
};

#endif