// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_VEHICLEUIINDICATOR_REC_HPP
#define DB_VEHICLEUIINDICATOR_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct VehicleUIIndicatorRec {
	static constexpr uint32_t columnCount = 2;
	static constexpr uint32_t rowSize = 8;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_BackgroundTexture;

	static const char* GetFilename() {
		return "DBFilesClient\\VehicleUIIndicator.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t BackgroundTextureOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &BackgroundTextureOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_BackgroundTexture = &stringBuffer[BackgroundTextureOfs];
		} else {
			this->m_BackgroundTexture = "";
		}

		return true;
	}
};

#endif