// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/VehicleSeatRec.hpp"

const char* VehicleSeatRec::GetFilename() {
    return "DBFilesClient\\VehicleSeat.dbc";
}

int32_t VehicleSeatRec::GetID() {
    return this->m_ID;
}

bool VehicleSeatRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_001, sizeof(this->m_field_3_3_5_12213_001), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_attachmentID, sizeof(this->m_attachmentID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_attachmentOffset[0], sizeof(m_attachmentOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_attachmentOffset[1], sizeof(m_attachmentOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_attachmentOffset[2], sizeof(m_attachmentOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_004, sizeof(this->m_field_3_3_5_12213_004), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterSpeed, sizeof(this->m_enterSpeed), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterGravity, sizeof(this->m_enterGravity), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterMinDuration, sizeof(this->m_enterMinDuration), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterMaxDuration, sizeof(this->m_enterMaxDuration), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterMinArcHeight, sizeof(this->m_enterMinArcHeight), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterMaxArcHeight, sizeof(this->m_enterMaxArcHeight), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterAnimStart, sizeof(this->m_enterAnimStart), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterAnimLoop, sizeof(this->m_enterAnimLoop), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rideAnimStart, sizeof(this->m_rideAnimStart), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rideAnimLoop, sizeof(this->m_rideAnimLoop), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rideUpperAnimStart, sizeof(this->m_rideUpperAnimStart), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rideUpperAnimLoop, sizeof(this->m_rideUpperAnimLoop), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_017, sizeof(this->m_field_3_3_5_12213_017), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitSpeed, sizeof(this->m_exitSpeed), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitGravity, sizeof(this->m_exitGravity), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitMinDuration, sizeof(this->m_exitMinDuration), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitMaxDuration, sizeof(this->m_exitMaxDuration), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitMinArcHeight, sizeof(this->m_exitMinArcHeight), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitMaxArcHeight, sizeof(this->m_exitMaxArcHeight), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitAnimStart, sizeof(this->m_exitAnimStart), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitAnimLoop, sizeof(this->m_exitAnimLoop), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_exitAnimEnd, sizeof(this->m_exitAnimEnd), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_027, sizeof(this->m_field_3_3_5_12213_027), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_passengerPitch, sizeof(this->m_passengerPitch), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_029, sizeof(this->m_field_3_3_5_12213_029), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_passengerAttachmentID, sizeof(this->m_passengerAttachmentID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_vehicleEnterAnim, sizeof(this->m_vehicleEnterAnim), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_vehicleExitAnim, sizeof(this->m_vehicleExitAnim), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_vehicleRideAnimLoop, sizeof(this->m_vehicleRideAnimLoop), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_034, sizeof(this->m_field_3_3_5_12213_034), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_vehicleExitAnimBone, sizeof(this->m_vehicleExitAnimBone), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_vehicleEnterAnimBone, sizeof(this->m_vehicleEnterAnimBone), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_037, sizeof(this->m_field_3_3_5_12213_037), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_038, sizeof(this->m_field_3_3_5_12213_038), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_vehicleAbilityDisplay, sizeof(this->m_vehicleAbilityDisplay), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_enterUisoundID, sizeof(this->m_enterUisoundID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_041, sizeof(this->m_field_3_3_5_12213_041), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_uiSkin, sizeof(this->m_uiSkin), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_043, sizeof(this->m_field_3_3_5_12213_043), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_044, sizeof(this->m_field_3_3_5_12213_044), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_045, sizeof(this->m_field_3_3_5_12213_045), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_046, sizeof(this->m_field_3_3_5_12213_046), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_047, sizeof(this->m_field_3_3_5_12213_047), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_048, sizeof(this->m_field_3_3_5_12213_048), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_049, sizeof(this->m_field_3_3_5_12213_049), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_050, sizeof(this->m_field_3_3_5_12213_050), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_051, sizeof(this->m_field_3_3_5_12213_051), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_052, sizeof(this->m_field_3_3_5_12213_052), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_053, sizeof(this->m_field_3_3_5_12213_053), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_054, sizeof(this->m_field_3_3_5_12213_054), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_field_3_3_5_12213_055, sizeof(this->m_field_3_3_5_12213_055), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
