// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_VEHICLESEAT_REC_HPP
#define DB_VEHICLESEAT_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct VehicleSeatRec {
	static constexpr uint32_t columnCount = 58;
	static constexpr uint32_t rowSize = 232;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	float m_Field_3_3_5_12213_001;
	int32_t m_AttachmentID;
	float m_AttachmentOffset[3];
	float m_Field_3_3_5_12213_004;
	float m_EnterSpeed;
	float m_EnterGravity;
	float m_EnterMinDuration;
	float m_EnterMaxDuration;
	float m_EnterMinArcHeight;
	float m_EnterMaxArcHeight;
	int32_t m_EnterAnimStart;
	int32_t m_EnterAnimLoop;
	int32_t m_RideAnimStart;
	int32_t m_RideAnimLoop;
	int32_t m_RideUpperAnimStart;
	int32_t m_RideUpperAnimLoop;
	float m_Field_3_3_5_12213_017;
	float m_ExitSpeed;
	float m_ExitGravity;
	float m_ExitMinDuration;
	float m_ExitMaxDuration;
	float m_ExitMinArcHeight;
	float m_ExitMaxArcHeight;
	int32_t m_ExitAnimStart;
	int32_t m_ExitAnimLoop;
	int32_t m_ExitAnimEnd;
	float m_Field_3_3_5_12213_027;
	float m_PassengerPitch;
	float m_Field_3_3_5_12213_029;
	int32_t m_PassengerAttachmentID;
	int32_t m_VehicleEnterAnim;
	int32_t m_VehicleExitAnim;
	int32_t m_VehicleRideAnimLoop;
	int32_t m_Field_3_3_5_12213_034;
	int32_t m_VehicleExitAnimBone;
	int32_t m_VehicleEnterAnimBone;
	float m_Field_3_3_5_12213_037;
	float m_Field_3_3_5_12213_038;
	int32_t m_VehicleAbilityDisplay;
	int32_t m_EnterUISoundID;
	int32_t m_Field_3_3_5_12213_041;
	int32_t m_UiSkin;
	float m_Field_3_3_5_12213_043;
	float m_Field_3_3_5_12213_044;
	float m_Field_3_3_5_12213_045;
	int32_t m_Field_3_3_5_12213_046;
	float m_Field_3_3_5_12213_047;
	float m_Field_3_3_5_12213_048;
	float m_Field_3_3_5_12213_049;
	float m_Field_3_3_5_12213_050;
	float m_Field_3_3_5_12213_051;
	float m_Field_3_3_5_12213_052;
	float m_Field_3_3_5_12213_053;
	float m_Field_3_3_5_12213_054;
	float m_Field_3_3_5_12213_055;

	static const char* GetFilename() {
		return "DBFilesClient\\VehicleSeat.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_001, sizeof(this->m_Field_3_3_5_12213_001), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AttachmentID, sizeof(this->m_AttachmentID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AttachmentOffset[0], sizeof(m_AttachmentOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AttachmentOffset[1], sizeof(m_AttachmentOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AttachmentOffset[2], sizeof(m_AttachmentOffset[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_004, sizeof(this->m_Field_3_3_5_12213_004), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterSpeed, sizeof(this->m_EnterSpeed), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterGravity, sizeof(this->m_EnterGravity), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterMinDuration, sizeof(this->m_EnterMinDuration), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterMaxDuration, sizeof(this->m_EnterMaxDuration), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterMinArcHeight, sizeof(this->m_EnterMinArcHeight), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterMaxArcHeight, sizeof(this->m_EnterMaxArcHeight), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterAnimStart, sizeof(this->m_EnterAnimStart), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterAnimLoop, sizeof(this->m_EnterAnimLoop), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RideAnimStart, sizeof(this->m_RideAnimStart), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RideAnimLoop, sizeof(this->m_RideAnimLoop), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RideUpperAnimStart, sizeof(this->m_RideUpperAnimStart), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_RideUpperAnimLoop, sizeof(this->m_RideUpperAnimLoop), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_017, sizeof(this->m_Field_3_3_5_12213_017), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitSpeed, sizeof(this->m_ExitSpeed), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitGravity, sizeof(this->m_ExitGravity), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitMinDuration, sizeof(this->m_ExitMinDuration), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitMaxDuration, sizeof(this->m_ExitMaxDuration), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitMinArcHeight, sizeof(this->m_ExitMinArcHeight), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitMaxArcHeight, sizeof(this->m_ExitMaxArcHeight), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitAnimStart, sizeof(this->m_ExitAnimStart), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitAnimLoop, sizeof(this->m_ExitAnimLoop), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExitAnimEnd, sizeof(this->m_ExitAnimEnd), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_027, sizeof(this->m_Field_3_3_5_12213_027), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PassengerPitch, sizeof(this->m_PassengerPitch), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_029, sizeof(this->m_Field_3_3_5_12213_029), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PassengerAttachmentID, sizeof(this->m_PassengerAttachmentID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VehicleEnterAnim, sizeof(this->m_VehicleEnterAnim), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VehicleExitAnim, sizeof(this->m_VehicleExitAnim), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VehicleRideAnimLoop, sizeof(this->m_VehicleRideAnimLoop), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_034, sizeof(this->m_Field_3_3_5_12213_034), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VehicleExitAnimBone, sizeof(this->m_VehicleExitAnimBone), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VehicleEnterAnimBone, sizeof(this->m_VehicleEnterAnimBone), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_037, sizeof(this->m_Field_3_3_5_12213_037), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_038, sizeof(this->m_Field_3_3_5_12213_038), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_VehicleAbilityDisplay, sizeof(this->m_VehicleAbilityDisplay), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_EnterUISoundID, sizeof(this->m_EnterUISoundID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_041, sizeof(this->m_Field_3_3_5_12213_041), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_UiSkin, sizeof(this->m_UiSkin), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_043, sizeof(this->m_Field_3_3_5_12213_043), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_044, sizeof(this->m_Field_3_3_5_12213_044), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_045, sizeof(this->m_Field_3_3_5_12213_045), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_046, sizeof(this->m_Field_3_3_5_12213_046), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_047, sizeof(this->m_Field_3_3_5_12213_047), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_048, sizeof(this->m_Field_3_3_5_12213_048), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_049, sizeof(this->m_Field_3_3_5_12213_049), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_050, sizeof(this->m_Field_3_3_5_12213_050), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_051, sizeof(this->m_Field_3_3_5_12213_051), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_052, sizeof(this->m_Field_3_3_5_12213_052), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_053, sizeof(this->m_Field_3_3_5_12213_053), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_054, sizeof(this->m_Field_3_3_5_12213_054), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Field_3_3_5_12213_055, sizeof(this->m_Field_3_3_5_12213_055), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif