// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_REC_VIDEO_HARDWARE_REC_HPP
#define DB_REC_VIDEO_HARDWARE_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

class VideoHardwareRec {
    public:
        int32_t m_ID;
        int32_t m_vendorID;
        int32_t m_deviceID;
        int32_t m_farclipIdx;
        int32_t m_terrainLoddistIdx;
        int32_t m_terrainShadowLod;
        int32_t m_detailDoodadDensityIdx;
        int32_t m_detailDoodadAlpha;
        int32_t m_animatingDoodadIdx;
        int32_t m_trilinear;
        int32_t m_numLights;
        int32_t m_specularity;
        int32_t m_waterLodidx;
        int32_t m_particleDensityIdx;
        int32_t m_unitDrawDistIdx;
        int32_t m_smallCullDistIdx;
        int32_t m_resolutionIdx;
        int32_t m_baseMipLevel;
        const char* m_oglOverrides;
        const char* m_d3DOverrides;
        int32_t m_fixLag;
        int32_t m_multisample;
        int32_t m_atlasdisable;

        static const char* GetFilename();
        static int32_t GetNumColumns();
        static int32_t GetRowSize();
        static bool NeedIDAssigned();
        int32_t GetID();
        void SetID(int32_t id);
        bool Read(SFile* f, const char* stringBuffer);
};

#endif