// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/WeaponImpactSoundsRec.hpp"

const char* WeaponImpactSoundsRec::GetFilename() {
    return "DBFilesClient\\WeaponImpactSounds.dbc";
}

bool WeaponImpactSoundsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_WeaponSubClassID, sizeof(this->m_WeaponSubClassID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ParrySoundType, sizeof(this->m_ParrySoundType), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[0], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[1], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[2], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[3], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[4], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[5], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[6], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[7], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[8], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_ImpactSoundID[9], sizeof(m_ImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[0], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[1], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[2], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[3], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[4], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[5], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[6], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[7], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[8], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_CritImpactSoundID[9], sizeof(m_CritImpactSoundID[0]), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
