// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_WORLDCHUNKSOUNDS_REC_HPP
#define DB_WORLDCHUNKSOUNDS_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct WorldChunkSoundsRec {
	static constexpr uint32_t columnCount = 9;
	static constexpr uint32_t rowSize = 36;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_ChunkX;
	int32_t m_ChunkY;
	int32_t m_SubchunkX;
	int32_t m_SubchunkY;
	int32_t m_ZoneIntroMusicID;
	int32_t m_ZoneMusicID;
	int32_t m_SoundAmbienceID;
	int32_t m_SoundProviderPreferencesID;

	static const char* GetFilename() {
		return "DBFilesClient\\WorldChunkSounds.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ChunkX, sizeof(this->m_ChunkX), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ChunkY, sizeof(this->m_ChunkY), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SubchunkX, sizeof(this->m_SubchunkX), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SubchunkY, sizeof(this->m_SubchunkY), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ZoneIntroMusicID, sizeof(this->m_ZoneIntroMusicID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ZoneMusicID, sizeof(this->m_ZoneMusicID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundAmbienceID, sizeof(this->m_SoundAmbienceID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SoundProviderPreferencesID, sizeof(this->m_SoundProviderPreferencesID), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		return true;
	}
};

#endif