// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/WorldMapContinentRec.hpp"

const char* WorldMapContinentRec::GetFilename() {
    return "DBFilesClient\\WorldMapContinent.dbc";
}

int32_t WorldMapContinentRec::GetNumColumns() {
    return 14;
}

int32_t WorldMapContinentRec::GetRowSize() {
    return 56;
}

bool WorldMapContinentRec::NeedIDAssigned() {
    return false;
}

int32_t WorldMapContinentRec::GetID() {
    return this->m_ID;
}

void WorldMapContinentRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool WorldMapContinentRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_mapID, sizeof(this->m_mapID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_leftBoundary, sizeof(this->m_leftBoundary), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_rightBoundary, sizeof(this->m_rightBoundary), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_topBoundary, sizeof(this->m_topBoundary), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_bottomBoundary, sizeof(this->m_bottomBoundary), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_continentOffset[0], sizeof(m_continentOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_continentOffset[1], sizeof(m_continentOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_scale, sizeof(this->m_scale), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_taxiMin[0], sizeof(m_taxiMin[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_taxiMin[1], sizeof(m_taxiMin[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_taxiMax[0], sizeof(m_taxiMax[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_taxiMax[1], sizeof(m_taxiMax[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_worldMapID, sizeof(this->m_worldMapID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
