// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_WORLDSTATEUI_REC_HPP
#define DB_WORLDSTATEUI_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct WorldStateUIRec {
	static constexpr uint32_t columnCount = 63;
	static constexpr uint32_t rowSize = 252;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	int32_t m_MapID;
	int32_t m_AreaID;
	int32_t m_PhaseShift;
	const char* m_Icon;
	const char* m_String_lang;
	const char* m_Tooltip_lang;
	int32_t m_StateVariable;
	int32_t m_Type;
	const char* m_DynamicIcon;
	const char* m_DynamicTooltip_lang;
	const char* m_ExtendedUI;
	int32_t m_ExtendedUIStateVariable[3];

	static const char* GetFilename() {
		return "DBFilesClient\\WorldStateUI.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t IconOfs;
		uint32_t String_langOfs[16];
		uint32_t String_langMask;
		uint32_t Tooltip_langOfs[16];
		uint32_t Tooltip_langMask;
		uint32_t DynamicIconOfs;
		uint32_t DynamicTooltip_langOfs[16];
		uint32_t DynamicTooltip_langMask;
		uint32_t ExtendedUIOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_MapID, sizeof(this->m_MapID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_AreaID, sizeof(this->m_AreaID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_PhaseShift, sizeof(this->m_PhaseShift), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &IconOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &String_langMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &Tooltip_langMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_StateVariable, sizeof(this->m_StateVariable), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Type, sizeof(this->m_Type), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicIconOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[0], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[1], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[2], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[3], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[4], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[5], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[6], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[7], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[8], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[9], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[10], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[11], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[12], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[13], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[14], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langOfs[15], sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &DynamicTooltip_langMask, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &ExtendedUIOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExtendedUIStateVariable[0], sizeof(m_ExtendedUIStateVariable[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExtendedUIStateVariable[1], sizeof(m_ExtendedUIStateVariable[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_ExtendedUIStateVariable[2], sizeof(m_ExtendedUIStateVariable[0]), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_Icon = &stringBuffer[IconOfs];
			this->m_String_lang = &stringBuffer[String_langOfs[CURRENT_LANGUAGE]];
			this->m_Tooltip_lang = &stringBuffer[Tooltip_langOfs[CURRENT_LANGUAGE]];
			this->m_DynamicIcon = &stringBuffer[DynamicIconOfs];
			this->m_DynamicTooltip_lang = &stringBuffer[DynamicTooltip_langOfs[CURRENT_LANGUAGE]];
			this->m_ExtendedUI = &stringBuffer[ExtendedUIOfs];
		} else {
			this->m_Icon = "";
			this->m_String_lang = "";
			this->m_Tooltip_lang = "";
			this->m_DynamicIcon = "";
			this->m_DynamicTooltip_lang = "";
			this->m_ExtendedUI = "";
		}

		return true;
	}
};

#endif