// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/WorldMapTransformsRec.hpp"

const char* WorldMapTransformsRec::GetFilename() {
    return "DBFilesClient\\WorldMapTransforms.dbc";
}

bool WorldMapTransformsRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_MapID, sizeof(this->m_MapID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RegionMin[0], sizeof(m_RegionMin[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RegionMin[1], sizeof(m_RegionMin[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RegionMax[0], sizeof(m_RegionMax[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RegionMax[1], sizeof(m_RegionMax[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_NewMapID, sizeof(this->m_NewMapID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RegionOffset[0], sizeof(m_RegionOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_RegionOffset[1], sizeof(m_RegionOffset[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_NewDungeonMapID, sizeof(this->m_NewDungeonMapID), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
