// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/WorldMapOverlayRec.hpp"
#include "util/SFile.hpp"

const char* WorldMapOverlayRec::GetFilename() {
    return "DBFilesClient\\WorldMapOverlay.dbc";
}

uint32_t WorldMapOverlayRec::GetNumColumns() {
    return 17;
}

uint32_t WorldMapOverlayRec::GetRowSize() {
    return 68;
}

bool WorldMapOverlayRec::NeedIDAssigned() {
    return false;
}

int32_t WorldMapOverlayRec::GetID() {
    return this->m_ID;
}

void WorldMapOverlayRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool WorldMapOverlayRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t textureNameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_mapAreaID, sizeof(this->m_mapAreaID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_areaID[0], sizeof(m_areaID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_areaID[1], sizeof(m_areaID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_areaID[2], sizeof(m_areaID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_areaID[3], sizeof(m_areaID[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_mapPointX, sizeof(this->m_mapPointX), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_mapPointY, sizeof(this->m_mapPointY), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &textureNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_textureWidth, sizeof(this->m_textureWidth), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_textureHeight, sizeof(this->m_textureHeight), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_offsetX, sizeof(this->m_offsetX), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_offsetY, sizeof(this->m_offsetY), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hitRectTop, sizeof(this->m_hitRectTop), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hitRectLeft, sizeof(this->m_hitRectLeft), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hitRectBottom, sizeof(this->m_hitRectBottom), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_hitRectRight, sizeof(this->m_hitRectRight), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_textureName = &stringBuffer[textureNameOfs];
    } else {
        this->m_textureName = "";
    }

    return true;
}
