// DO NOT EDIT: generated by whoa-autocode
#ifndef DB_ZONEMUSIC_REC_HPP
#define DB_ZONEMUSIC_REC_HPP

#include "util/SFile.hpp"
#include <cstdint>

struct ZoneMusicRec {
	static constexpr uint32_t columnCount = 8;
	static constexpr uint32_t rowSize = 32;
	static constexpr bool indexIsID = false;

	int32_t m_ID;
	const char* m_SetName;
	int32_t m_SilenceIntervalMin[2];
	int32_t m_SilenceIntervalMax[2];
	int32_t m_Sounds[2];

	static const char* GetFilename() {
		return "DBFilesClient\\ZoneMusic.dbc";
	}

	bool Read(SFile* f, const char* stringBuffer) {
		uint32_t SetNameOfs;

		if (
			!SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &SetNameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SilenceIntervalMin[0], sizeof(m_SilenceIntervalMin[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SilenceIntervalMin[1], sizeof(m_SilenceIntervalMin[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SilenceIntervalMax[0], sizeof(m_SilenceIntervalMax[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_SilenceIntervalMax[1], sizeof(m_SilenceIntervalMax[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Sounds[0], sizeof(m_Sounds[0]), nullptr, nullptr, nullptr)
			|| !SFile::Read(f, &this->m_Sounds[1], sizeof(m_Sounds[0]), nullptr, nullptr, nullptr)
		) {
			return false;
		}

		if (stringBuffer) {
			this->m_SetName = &stringBuffer[SetNameOfs];
		} else {
			this->m_SetName = "";
		}

		return true;
	}
};

#endif