// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ZoneLightPointRec.hpp"
#include "util/SFile.hpp"

const char* ZoneLightPointRec::GetFilename() {
    return "DBFilesClient\\ZoneLightPoint.dbc";
}

uint32_t ZoneLightPointRec::GetNumColumns() {
    return 5;
}

uint32_t ZoneLightPointRec::GetRowSize() {
    return 20;
}

bool ZoneLightPointRec::NeedIDAssigned() {
    return false;
}

int32_t ZoneLightPointRec::GetID() {
    return this->m_ID;
}

void ZoneLightPointRec::SetID(int32_t id) {
    this->m_ID = id;
}

bool ZoneLightPointRec::Read(SFile* f, const char* stringBuffer) {
    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_zoneLightID, sizeof(this->m_zoneLightID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_pos[0], sizeof(m_pos[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_pos[1], sizeof(m_pos[0]), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_pointOrder, sizeof(this->m_pointOrder), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    return true;
}
