// DO NOT EDIT: generated by whoa-autocode
#include "db/rec/ZoneIntroMusicTableRec.hpp"

const char* ZoneIntroMusicTableRec::GetFilename() {
    return "DBFilesClient\\ZoneIntroMusicTable.dbc";
}

bool ZoneIntroMusicTableRec::Read(SFile* f, const char* stringBuffer) {
    uint32_t NameOfs;

    if (
        !SFile::Read(f, &this->m_ID, sizeof(this->m_ID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &NameOfs, sizeof(uint32_t), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_SoundID, sizeof(this->m_SoundID), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_Priority, sizeof(this->m_Priority), nullptr, nullptr, nullptr)
        || !SFile::Read(f, &this->m_MinDelayMinutes, sizeof(this->m_MinDelayMinutes), nullptr, nullptr, nullptr)
    ) {
        return false;
    }

    if (stringBuffer) {
        this->m_Name = &stringBuffer[NameOfs];
    } else {
        this->m_Name = "";
    }

    return true;
}
