// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool AnimReplacementRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SrcAnimID, sizeof(m_SrcAnimID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_DstAnimID, sizeof(m_DstAnimID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ParentAnimReplacementSetID, sizeof(m_ParentAnimReplacementSetID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading AnimReplacement", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* AnimReplacementRec::GetFilename() {
	return "DBFilesClient\\AnimReplacement.dbc";
}
