// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool AreaGroupRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID[0], sizeof(m_AreaID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID[1], sizeof(m_AreaID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID[2], sizeof(m_AreaID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID[3], sizeof(m_AreaID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID[4], sizeof(m_AreaID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AreaID[5], sizeof(m_AreaID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_NextAreaID, sizeof(m_NextAreaID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading AreaGroup", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* AreaGroupRec::GetFilename() {
	return "DBFilesClient\\AreaGroup.dbc";
}
