// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool DeclinedWordRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempWordIndices[1];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Word_bitmask, sizeof(uint32_t), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading DeclinedWord", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_Word = &stringBuffer[tempWordIndices[0]];
		return true;
	}
	return true;
}

const char* DeclinedWordRec::GetFilename() {
	return "DBFilesClient\\DeclinedWord.dbc";
}
