// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool DungeonMapChunkRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MapID, sizeof(m_MapID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_WMOGroupID, sizeof(m_WMOGroupID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_DungeonMapID, sizeof(m_DungeonMapID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MinZ, sizeof(m_MinZ), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading DungeonMapChunk", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* DungeonMapChunkRec::GetFilename() {
	return "DBFilesClient\\DungeonMapChunk.dbc";
}
