// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool HelmetGeosetVisDataRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[0], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[1], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[2], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[3], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[4], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[5], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_HideGeoset[6], sizeof(m_HideGeoset[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading HelmetGeosetVisData", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* HelmetGeosetVisDataRec::GetFilename() {
	return "DBFilesClient\\HelmetGeosetVisData.dbc";
}
