// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool ItemCondExtCostsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CondExtendedCost, sizeof(m_CondExtendedCost), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ItemExtendedCostEntry, sizeof(m_ItemExtendedCostEntry), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ArenaSeason, sizeof(m_ArenaSeason), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading ItemCondExtCosts", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* ItemCondExtCostsRec::GetFilename() {
	return "DBFilesClient\\ItemCondExtCosts.dbc";
}
