// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool ObjectEffectRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempNameIndices[1];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Name_bitmask, sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ObjectEffectGroupID, sizeof(m_ObjectEffectGroupID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_TriggerType, sizeof(m_TriggerType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EventType, sizeof(m_EventType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectRecType, sizeof(m_EffectRecType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectRecID, sizeof(m_EffectRecID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Attachment, sizeof(m_Attachment), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Offset[0], sizeof(m_Offset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Offset[1], sizeof(m_Offset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Offset[2], sizeof(m_Offset[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ObjectEffectModifierID, sizeof(m_ObjectEffectModifierID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading ObjectEffect", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_Name = &stringBuffer[tempNameIndices[0]];
		return true;
	}
	return true;
}

const char* ObjectEffectRec::GetFilename() {
	return "DBFilesClient\\ObjectEffect.dbc";
}
