// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SkillCostsDataRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SkillCostsID, sizeof(m_SkillCostsID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Cost[0], sizeof(m_Cost[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Cost[1], sizeof(m_Cost[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Cost[2], sizeof(m_Cost[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SkillCostsData", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SkillCostsDataRec::GetFilename() {
	return "DBFilesClient\\SkillCostsData.dbc";
}
