// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellShapeshiftRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ShapeshiftExclude[0], sizeof(m_ShapeshiftExclude[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ShapeshiftExclude[1], sizeof(m_ShapeshiftExclude[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ShapeshiftMask[0], sizeof(m_ShapeshiftMask[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ShapeshiftMask[1], sizeof(m_ShapeshiftMask[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_StanceBarOrder, sizeof(m_StanceBarOrder), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellShapeshift", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellShapeshiftRec::GetFilename() {
	return "DBFilesClient\\SpellShapeshift.dbc";
}
