// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellItemEnchantmentRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempName_langIndices[16];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Charges, sizeof(m_Charges), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Effect[0], sizeof(m_Effect[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Effect[1], sizeof(m_Effect[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Effect[2], sizeof(m_Effect[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectPointsMin[0], sizeof(m_EffectPointsMin[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectPointsMin[1], sizeof(m_EffectPointsMin[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectPointsMin[2], sizeof(m_EffectPointsMin[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectPointsMax[0], sizeof(m_EffectPointsMax[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectPointsMax[1], sizeof(m_EffectPointsMax[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectPointsMax[2], sizeof(m_EffectPointsMax[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectArg[0], sizeof(m_EffectArg[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectArg[1], sizeof(m_EffectArg[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_EffectArg[2], sizeof(m_EffectArg[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[1], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[2], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[3], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[4], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[5], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[6], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[7], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[8], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[9], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[10], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[11], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[12], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[13], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[14], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempName_langIndices[15], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Name_lang_bitmask, sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ItemVisual, sizeof(m_ItemVisual), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Flags, sizeof(m_Flags), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Src_itemID, sizeof(m_Src_itemID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Condition_ID, sizeof(m_Condition_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiredSkillID, sizeof(m_RequiredSkillID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiredSkillRank, sizeof(m_RequiredSkillRank), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MinLevel, sizeof(m_MinLevel), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellItemEnchantment", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_Name_lang[0] = &stringBuffer[tempName_langIndices[0]];
		m_Name_lang[1] = &stringBuffer[tempName_langIndices[1]];
		m_Name_lang[2] = &stringBuffer[tempName_langIndices[2]];
		m_Name_lang[3] = &stringBuffer[tempName_langIndices[3]];
		m_Name_lang[4] = &stringBuffer[tempName_langIndices[4]];
		m_Name_lang[5] = &stringBuffer[tempName_langIndices[5]];
		m_Name_lang[6] = &stringBuffer[tempName_langIndices[6]];
		m_Name_lang[7] = &stringBuffer[tempName_langIndices[7]];
		m_Name_lang[8] = &stringBuffer[tempName_langIndices[8]];
		m_Name_lang[9] = &stringBuffer[tempName_langIndices[9]];
		m_Name_lang[10] = &stringBuffer[tempName_langIndices[10]];
		m_Name_lang[11] = &stringBuffer[tempName_langIndices[11]];
		m_Name_lang[12] = &stringBuffer[tempName_langIndices[12]];
		m_Name_lang[13] = &stringBuffer[tempName_langIndices[13]];
		m_Name_lang[14] = &stringBuffer[tempName_langIndices[14]];
		m_Name_lang[15] = &stringBuffer[tempName_langIndices[15]];
		return true;
	}
	return true;
}

const char* SpellItemEnchantmentRec::GetFilename() {
	return "DBFilesClient\\SpellItemEnchantment.dbc";
}
