// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellTotemsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiredTotemCategoryID[0], sizeof(m_RequiredTotemCategoryID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiredTotemCategoryID[1], sizeof(m_RequiredTotemCategoryID[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Totem[0], sizeof(m_Totem[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Totem[1], sizeof(m_Totem[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellTotems", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellTotemsRec::GetFilename() {
	return "DBFilesClient\\SpellTotems.dbc";
}
