// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellEffectCameraShakesRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CameraShake[0], sizeof(m_CameraShake[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CameraShake[1], sizeof(m_CameraShake[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CameraShake[2], sizeof(m_CameraShake[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellEffectCameraShakes", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellEffectCameraShakesRec::GetFilename() {
	return "DBFilesClient\\SpellEffectCameraShakes.dbc";
}
