// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellInterruptsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AuraInterruptFlags[0], sizeof(m_AuraInterruptFlags[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_AuraInterruptFlags[1], sizeof(m_AuraInterruptFlags[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ChannelInterruptFlags[0], sizeof(m_ChannelInterruptFlags[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ChannelInterruptFlags[1], sizeof(m_ChannelInterruptFlags[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_InterruptFlags, sizeof(m_InterruptFlags), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellInterrupts", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellInterruptsRec::GetFilename() {
	return "DBFilesClient\\SpellInterrupts.dbc";
}
