// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellCastingRequirementsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_FacingCasterFlags, sizeof(m_FacingCasterFlags), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MinFactionID, sizeof(m_MinFactionID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MinReputation, sizeof(m_MinReputation), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiredAreasID, sizeof(m_RequiredAreasID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiredAuraVision, sizeof(m_RequiredAuraVision), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_RequiresSpellFocus, sizeof(m_RequiresSpellFocus), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellCastingRequirements", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellCastingRequirementsRec::GetFilename() {
	return "DBFilesClient\\SpellCastingRequirements.dbc";
}
