// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellScalingRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CastTimeMin, sizeof(m_CastTimeMin), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CastTimeMax, sizeof(m_CastTimeMax), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CastTimeMaxLevel, sizeof(m_CastTimeMaxLevel), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Class, sizeof(m_Class), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Coefficient[0], sizeof(m_Coefficient[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Coefficient[1], sizeof(m_Coefficient[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Coefficient[2], sizeof(m_Coefficient[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Variance[0], sizeof(m_Variance[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Variance[1], sizeof(m_Variance[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Variance[2], sizeof(m_Variance[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ComboPointsCoefficient[0], sizeof(m_ComboPointsCoefficient[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ComboPointsCoefficient[1], sizeof(m_ComboPointsCoefficient[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ComboPointsCoefficient[2], sizeof(m_ComboPointsCoefficient[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_NerfFactor, sizeof(m_NerfFactor), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_NerfMaxLevel, sizeof(m_NerfMaxLevel), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellScaling", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellScalingRec::GetFilename() {
	return "DBFilesClient\\SpellScaling.dbc";
}
