// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellPowerRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ManaCost, sizeof(m_ManaCost), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ManaCostPerLevel, sizeof(m_ManaCostPerLevel), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_PowerCost, sizeof(m_PowerCost), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ManaPerSecond, sizeof(m_ManaPerSecond), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_PowerDisplayID, sizeof(m_PowerDisplayID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellPower", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellPowerRec::GetFilename() {
	return "DBFilesClient\\SpellPower.dbc";
}
