// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool SpellTargetRestrictionsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MaxTargets, sizeof(m_MaxTargets), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_MaxTargetLevel, sizeof(m_MaxTargetLevel), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_TargetCreatureType, sizeof(m_TargetCreatureType), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Targets, sizeof(m_Targets), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading SpellTargetRestrictions", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* SpellTargetRestrictionsRec::GetFilename() {
	return "DBFilesClient\\SpellTargetRestrictions.dbc";
}
