// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool TaxiPathRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_FromTaxiNode, sizeof(m_FromTaxiNode), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ToTaxiNode, sizeof(m_ToTaxiNode), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Cost, sizeof(m_Cost), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading TaxiPath", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* TaxiPathRec::GetFilename() {
	return "DBFilesClient\\TaxiPath.dbc";
}
