// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool TransportRotationRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GameObjectsID, sizeof(m_GameObjectsID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_TimeIndex, sizeof(m_TimeIndex), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Rot[0], sizeof(m_Rot[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Rot[1], sizeof(m_Rot[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Rot[2], sizeof(m_Rot[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_Rot[3], sizeof(m_Rot[0]), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading TransportRotation", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* TransportRotationRec::GetFilename() {
	return "DBFilesClient\\TransportRotation.dbc";
}
