// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool UnitBloodRec::Read(SFile* f, const char* stringBuffer) {
	uint32_t tempGroundBloodIndices[5];
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CombatBloodSpurtFront[0], sizeof(m_CombatBloodSpurtFront[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CombatBloodSpurtFront[1], sizeof(m_CombatBloodSpurtFront[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CombatBloodSpurtBack[0], sizeof(m_CombatBloodSpurtBack[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_CombatBloodSpurtBack[1], sizeof(m_CombatBloodSpurtBack[0]), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempGroundBloodIndices[0], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempGroundBloodIndices[1], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempGroundBloodIndices[2], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &tempGroundBloodIndices[3], sizeof(uint32_t), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_GroundBlood_bitmask, sizeof(uint32_t), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading UnitBlood", WARNING_COLOR);
		return false;
	}
	if (stringBuffer) {
		m_GroundBlood[0] = &stringBuffer[tempGroundBloodIndices[0]];
		m_GroundBlood[1] = &stringBuffer[tempGroundBloodIndices[1]];
		m_GroundBlood[2] = &stringBuffer[tempGroundBloodIndices[2]];
		m_GroundBlood[3] = &stringBuffer[tempGroundBloodIndices[3]];
		m_GroundBlood[4] = &stringBuffer[tempGroundBloodIndices[4]];
		return true;
	}
		m_GroundBlood[0] = "";
		m_GroundBlood[1] = "";
		m_GroundBlood[2] = "";
		m_GroundBlood[3] = "";
		m_GroundBlood[4] = "";
	return true;
}

const char* UnitBloodRec::GetFilename() {
	return "DBFilesClient\\UnitBlood.dbc";
}
