// DO NOT EDIT: generated by whoa_autocode

#include "db/ClientDefs.hpp"

bool WorldChunkSoundsRec::Read(SFile* f, const char* stringBuffer) {
	if (
		SFile::Read(f, &m_ID, sizeof(m_ID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ChunkX, sizeof(m_ChunkX), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ChunkY, sizeof(m_ChunkY), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SubchunkX, sizeof(m_SubchunkX), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SubchunkY, sizeof(m_SubchunkY), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ZoneIntroMusicID, sizeof(m_ZoneIntroMusicID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_ZoneMusicID, sizeof(m_ZoneMusicID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SoundAmbienceID, sizeof(m_SoundAmbienceID), nullptr, nullptr, nullptr) == 0 ||
		SFile::Read(f, &m_SoundProviderPreferencesID, sizeof(m_SoundProviderPreferencesID), nullptr, nullptr, nullptr) == 0
	)
	{
		ConsoleWrite("Error reading WorldChunkSounds", WARNING_COLOR);
		return false;
	}
	return true;
}

const char* WorldChunkSoundsRec::GetFilename() {
	return "DBFilesClient\\WorldChunkSounds.dbc";
}
